import 'package:DairyVikas/features/auth/registration_flow/data/model/dairy_setting_data_model.dart';
import 'package:DairyVikas/features/collection/data/model/collection_model.dart';
import 'package:DairyVikas/features/food/data/models/dealer_model.dart';
import 'package:DairyVikas/features/food/data/models/sale_model.dart';
import 'package:DairyVikas/features/food/data/models/stock_history_model.dart';
import 'package:DairyVikas/features/food/data/models/stock_model.dart';
import 'package:DairyVikas/features/invoices/data/model/invoice_model.dart';
import 'package:DairyVikas/features/khata/data/models/khatabook_user_model.dart';
import 'package:DairyVikas/features/milk_sale/data/models/milk_buyer_model.dart';
import 'package:DairyVikas/features/milk_sale/data/models/milk_sale_model.dart';
import 'package:DairyVikas/features/milk_suppliers/data/model/milk_supplier_model.dart';
import 'package:DairyVikas/features/notice_board/data/models/notice_post_model.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../features/rate_cart/data/model/rate_chart_model.dart';
import '../../features/rate_cart/presentation/chart_helpers/rate_chart_mapper.dart';

class AppState {
  static String dairyName = 'unavailable';
  static RxString vendorName = 'Dairy Vikas User'.obs;
  static String vendorDistrict = 'unknown';
  static String vendorState = 'unknown';
  static String appVersion = '';
  static double clrIncreaseStep = 1.0;
  static double baseAmount = 0.0;
  static bool isDairyAdded = false;
  static RxList dateRanges = [].obs;

  static bool isRateChartEdit = false;

  static bool isSupplierEdit = false;

  static bool isMilkBuyerEdit = false;
  static bool isCollectionEdit = false;
  static bool isMilkSaleEdit = false;
  static bool isDealerEdit = false;
  static bool isFoodStockEdit = false;
  static bool isFoodSaleEdit = false;
  static bool isNoticePostEdit = false;
  static bool iskhataCustomerEdit = false;
  static bool isPaymentSuccess = false;
  static RxList<MilkSupplierModel> milkSuppliers = <MilkSupplierModel>[].obs;
  static List<Map> rateChartCategories = [
    {"id": '1', "value": "collection"},
    {"id": '2', "value": "milk_sale"},
  ];
  static RxList<Map<String, dynamic>> shifts = <Map<String, dynamic>>[
    {"id": 1, "name": "morning"},
    {"id": 2, "name": "evening"},
    {"id": 3, "name": "morning_evening"},
  ].obs;

  static String chartIdForassignablesupplierScreen = '';
  static String customerTypeForassignablSupplierScreen = '';
  static String supplierCustomerType = 'supplier';
  static String buyerCustomerType = 'buyer';
  static DealerModel currentDealerForUpdate = DealerModel.empty();
  static MilkSupplierModel currentSupplierForUpdate = MilkSupplierModel.empty();
  static MilkBuyerModel currentBuyerForUpdate = MilkBuyerModel.empty();
  static CollectionModel currentCollectionforUpdate = CollectionModel.empty();
  static MilkSaleModel currentMilkSaleforUpdate = MilkSaleModel.empty();
  static RateChartModel currentRateChartForDetailsPage = RateChartModel.empty();
  static StockHistoryModel currentStockHistoryItem = StockHistoryModel.empty();
  static StockModel currentStock = StockModel.empty();
  static StockHistoryModel currentStockItem = StockHistoryModel.empty();
  static SaleModel currentFoodSale = SaleModel.empty();
  static NoticeModel currentNoticePostForUpdate = NoticeModel.empty();
  static KhatabookUserModel currentKhataBookCustomerForUpdate =
      KhatabookUserModel.empty();
  static InvoiceModel currentInvoiceForUpdate = InvoiceModel.empty();
  static RateChartMapper mapper = RateChartMapper();
  static BuildContext? context;
  static List<DairySettingDataModel> dairyCollectionTypes = [];
  static List<DairySettingDataModel> dairyMilkTypes = [];
  static List<DairySettingDataModel> dairyCollectionShifts = [];
  static List<DairySettingDataModel> dairyPaymentPeriods = [];
  static final List<Map<String, dynamic>> indianStates = [
    {
      "id": 1,
      "name_en": "Andhra Pradesh",
      "name_hi": "आंध्र प्रदेश",
      "districs": andhraPradeshDistricts,
    },
    {
      "id": 2,
      "name_en": "Arunachal Pradesh",
      "name_hi": "अरुणाचल प्रदेश",
      "districs": arunachalPradeshDistricts,
    },
    {"id": 3, "name_en": "Assam", "name_hi": "असम", "districs": assamDistricts},
    {
      "id": 4,
      "name_en": "Bihar",
      "name_hi": "बिहार",
      "districs": biharDistricts,
    },
    {
      "id": 5,
      "name_en": "Chhattisgarh",
      "name_hi": "छत्तीसगढ़",
      "districs": chhattisgarhDistricts,
    },
    {"id": 6, "name_en": "Goa", "name_hi": "गोवा", "districs": goaDistricts},
    {
      "id": 7,
      "name_en": "Gujarat",
      "name_hi": "गुजरात",
      "districs": gujaratDistricts,
    },
    {
      "id": 8,
      "name_en": "Haryana",
      "name_hi": "हरियाणा",
      "districs": haryanaDistricts,
    },
    {
      "id": 9,
      "name_en": "Himachal Pradesh",
      "name_hi": "हिमाचल प्रदेश",
      "districs": himachalPradeshDistricts,
    },
    {
      "id": 10,
      "name_en": "Jharkhand",
      "name_hi": "झारखंड",
      "districs": jharkhandDistricts,
    },
    {
      "id": 11,
      "name_en": "Karnataka",
      "name_hi": "कर्नाटक",
      "districs": karnatakaDistricts,
    },
    {
      "id": 12,
      "name_en": "Kerala",
      "name_hi": "केरल",
      "districs": keralaDistricts,
    },
    {
      "id": 13,
      "name_en": "Madhya Pradesh",
      "name_hi": "मध्य प्रदेश",
      "districs": madhyaPradeshDistricts,
    },
    {
      "id": 14,
      "name_en": "Maharashtra",
      "name_hi": "महाराष्ट्र",
      "districs": maharashtraDistricts,
    },
    {
      "id": 15,
      "name_en": "Manipur",
      "name_hi": "मणिपुर",
      "districs": manipurDistricts,
    },
    {
      "id": 16,
      "name_en": "Meghalaya",
      "name_hi": "मेघालय",
      "districs": meghalayaDistricts,
    },
    {
      "id": 17,
      "name_en": "Mizoram",
      "name_hi": "मिज़ोरम",
      "districs": mizoramDistricts,
    },
    {
      "id": 18,
      "name_en": "Nagaland",
      "name_hi": "नगालैंड",
      "districs": nagalandDistricts,
    },
    {
      "id": 19,
      "name_en": "Odisha",
      "name_hi": "ओडिशा",
      "districs": odishaDistricts,
    },
    {
      "id": 20,
      "name_en": "Punjab",
      "name_hi": "पंजाब",
      "districs": punjabDistricts,
    },
    {
      "id": 21,
      "name_en": "Rajasthan",
      "name_hi": "राजस्थान",
      "districs": rajasthanDistricts,
    },
    {
      "id": 22,
      "name_en": "Sikkim",
      "name_hi": "सिक्किम",
      "districs": sikkimDistricts,
    },
    {
      "id": 23,
      "name_en": "Tamil Nadu",
      "name_hi": "तमिलनाडु",
      "districs": tamilNaduDistricts,
    },
    {
      "id": 24,
      "name_en": "Telangana",
      "name_hi": "तेलंगाना",
      "districs": telanganaDistricts,
    },
    {
      "id": 25,
      "name_en": "Tripura",
      "name_hi": "त्रिपुरा",
      "districs": tripuraDistricts,
    },
    {
      "id": 26,
      "name_en": "Uttar Pradesh",
      "name_hi": "उत्तर प्रदेश",
      "districs": uttarPradeshDistricts,
    },
    {
      "id": 27,
      "name_en": "Uttarakhand",
      "name_hi": "उत्तराखंड",
      "districs": uttarakhandDistricts,
    },
    {
      "id": 28,
      "name_en": "West Bengal",
      "name_hi": "पश्चिम बंगाल",
      "districs": westBengalDistricts,
    },
  ];

  static final List<Map<String, dynamic>> andhraPradeshDistricts = [
    {
      "id": 1,
      "state_id": 1,
      "name_en": "Alluri Sitharama Raju",
      "name_hi": "अल्लूरी सीताराम राजू",
    },
    {"id": 2, "state_id": 1, "name_en": "Anakapalli", "name_hi": "अनकापल्ली"},
    {"id": 3, "state_id": 1, "name_en": "Anantapur", "name_hi": "अनंतपुर"},
    {"id": 4, "state_id": 1, "name_en": "Annamayya", "name_hi": "अन्नमय्या"},
    {"id": 5, "state_id": 1, "name_en": "Bapatla", "name_hi": "बापटल"},
    {"id": 6, "state_id": 1, "name_en": "Chittoor", "name_hi": "चित्तूर"},
    {
      "id": 7,
      "state_id": 1,
      "name_en": "East Godavari",
      "name_hi": "पूर्वी गोदावरी",
    },
    {"id": 8, "state_id": 1, "name_en": "Eluru", "name_hi": "एलूरु"},
    {"id": 9, "state_id": 1, "name_en": "Guntur", "name_hi": "गुंटूर"},
    {"id": 10, "state_id": 1, "name_en": "Kadapa", "name_hi": "कड़प्पा"},
    {"id": 11, "state_id": 1, "name_en": "Kakinada", "name_hi": "काकीनाडा"},
    {"id": 12, "state_id": 1, "name_en": "Konaseema", "name_hi": "कोनसीमा"},
    {"id": 13, "state_id": 1, "name_en": "Krishna", "name_hi": "कृष्णा"},
    {"id": 14, "state_id": 1, "name_en": "Kurnool", "name_hi": "कुर्नूल"},
    {"id": 15, "state_id": 1, "name_en": "Nandyal", "name_hi": "नंद्याल"},
    {"id": 16, "state_id": 1, "name_en": "Nellore", "name_hi": "नेल्लोर"},
    {"id": 17, "state_id": 1, "name_en": "NTR", "name_hi": "एनटीआर"},
    {"id": 18, "state_id": 1, "name_en": "Palnadu", "name_hi": "पलनाडु"},
    {"id": 19, "state_id": 1, "name_en": "Prakasam", "name_hi": "प्रकाशम"},
    {"id": 20, "state_id": 1, "name_en": "Rayachoti", "name_hi": "रायचोटी"},
    {"id": 21, "state_id": 1, "name_en": "Srikakulam", "name_hi": "श्रीकाकुलम"},
    {"id": 22, "state_id": 1, "name_en": "Tirupati", "name_hi": "तिरुपति"},
    {
      "id": 23,
      "state_id": 1,
      "name_en": "Visakhapatnam",
      "name_hi": "विशाखापत्तनम",
    },
    {"id": 24, "state_id": 1, "name_en": "Vizianagaram", "name_hi": "विजयनगरम"},
    {
      "id": 25,
      "state_id": 1,
      "name_en": "West Godavari",
      "name_hi": "पश्चिम गोदावरी",
    },
    {"id": 26, "state_id": 1, "name_en": "YSR", "name_hi": "वाईएसआर"},
  ];

  static final List<Map<String, dynamic>> arunachalPradeshDistricts = [
    {"id": 1, "state_id": 2, "name_en": "Tawang", "name_hi": "तवांग"},
    {
      "id": 2,
      "state_id": 2,
      "name_en": "West Kameng",
      "name_hi": "पश्चिम कामेंग",
    },
    {
      "id": 3,
      "state_id": 2,
      "name_en": "East Kameng",
      "name_hi": "पूर्व कामेंग",
    },
    {"id": 4, "state_id": 2, "name_en": "Papum Pare", "name_hi": "पापुम पारे"},
    {
      "id": 5,
      "state_id": 2,
      "name_en": "Kurung Kumey",
      "name_hi": "कुरुंग कुमे",
    },
    {"id": 6, "state_id": 2, "name_en": "Kra Daadi", "name_hi": "क्रा दादी"},
    {
      "id": 7,
      "state_id": 2,
      "name_en": "Lower Subansiri",
      "name_hi": "लोअर सुभंसिरी",
    },
    {
      "id": 8,
      "state_id": 2,
      "name_en": "Upper Subansiri",
      "name_hi": "अपर सुभंसिरी",
    },
    {
      "id": 9,
      "state_id": 2,
      "name_en": "West Siang",
      "name_hi": "पश्चिम सियांग",
    },
    {
      "id": 10,
      "state_id": 2,
      "name_en": "East Siang",
      "name_hi": "पूर्व सियांग",
    },
    {"id": 11, "state_id": 2, "name_en": "Siang", "name_hi": "सियांग"},
    {
      "id": 12,
      "state_id": 2,
      "name_en": "Upper Siang",
      "name_hi": "अपर सियांग",
    },
    {
      "id": 13,
      "state_id": 2,
      "name_en": "Lower Siang",
      "name_hi": "लोअर सियांग",
    },
    {
      "id": 14,
      "state_id": 2,
      "name_en": "Lower Dibang Valley",
      "name_hi": "लोअर डिबांग वैली",
    },
    {
      "id": 15,
      "state_id": 2,
      "name_en": "Dibang Valley",
      "name_hi": "डिबांग वैली",
    },
    {"id": 16, "state_id": 2, "name_en": "Anjaw", "name_hi": "अंजाव"},
    {"id": 17, "state_id": 2, "name_en": "Lohit", "name_hi": "लोहीत"},
    {"id": 18, "state_id": 2, "name_en": "Namsai", "name_hi": "नमसाई"},
    {"id": 19, "state_id": 2, "name_en": "Changlang", "name_hi": "चांगलांग"},
    {"id": 20, "state_id": 2, "name_en": "Tirap", "name_hi": "तिराप"},
    {"id": 21, "state_id": 2, "name_en": "Longding", "name_hi": "लॉन्गडिंग"},
  ];

  static final List<Map<String, dynamic>> assamDistricts = [
    {"id": 1, "state_id": 3, "name_en": "Baksa", "name_hi": "बक्सा"},
    {"id": 2, "state_id": 3, "name_en": "Barpeta", "name_hi": "बारपेटा"},
    {"id": 3, "state_id": 3, "name_en": "Biswanath", "name_hi": "बिस्वनाथ"},
    {"id": 4, "state_id": 3, "name_en": "Bongaigaon", "name_hi": "बोंगाईगांव"},
    {"id": 5, "state_id": 3, "name_en": "Cachar", "name_hi": "कच्छार"},
    {"id": 6, "state_id": 3, "name_en": "Charaideo", "name_hi": "चराईदेओ"},
    {"id": 7, "state_id": 3, "name_en": "Chirang", "name_hi": "चिरांग"},
    {"id": 8, "state_id": 3, "name_en": "Darrang", "name_hi": "डरांग"},
    {"id": 9, "state_id": 3, "name_en": "Dhemaji", "name_hi": "ढेमाजी"},
    {"id": 10, "state_id": 3, "name_en": "Dhubri", "name_hi": "धुबरी"},
    {"id": 11, "state_id": 3, "name_en": "Dibrugarh", "name_hi": "डिब्रूगढ़"},
    {"id": 12, "state_id": 3, "name_en": "Dima Hasao", "name_hi": "डिमा हासाओ"},
    {"id": 13, "state_id": 3, "name_en": "Goalpara", "name_hi": "गोलपारा"},
    {"id": 14, "state_id": 3, "name_en": "Golaghat", "name_hi": "गोलाघाट"},
    {"id": 15, "state_id": 3, "name_en": "Hailakandi", "name_hi": "हैलाकांडी"},
    {"id": 16, "state_id": 3, "name_en": "Hojai", "name_hi": "होजाई"},
    {"id": 17, "state_id": 3, "name_en": "Jorhat", "name_hi": "जोरहाट"},
    {"id": 18, "state_id": 3, "name_en": "Kamrup", "name_hi": "कांरुप"},
    {
      "id": 19,
      "state_id": 3,
      "name_en": "Kamrup Metropolitan",
      "name_hi": "कांरुप मेट्रोपॉलिटन",
    },
    {
      "id": 20,
      "state_id": 3,
      "name_en": "Karbi Anglong",
      "name_hi": "कारबी अंगलॉन्ग",
    },
    {"id": 21, "state_id": 3, "name_en": "Karimganj", "name_hi": "करीमगंज"},
    {"id": 22, "state_id": 3, "name_en": "Kokrajhar", "name_hi": "कोकराझार"},
    {"id": 23, "state_id": 3, "name_en": "Lakhimpur", "name_hi": "लखीमपुर"},
    {"id": 24, "state_id": 3, "name_en": "Majuli", "name_hi": "माजुली"},
    {"id": 25, "state_id": 3, "name_en": "Morigaon", "name_hi": "मोरिगांव"},
    {"id": 26, "state_id": 3, "name_en": "Nagaon", "name_hi": "नागांव"},
    {"id": 27, "state_id": 3, "name_en": "Nalbari", "name_hi": "नलबाड़ी"},
    {"id": 28, "state_id": 3, "name_en": "Sivasagar", "name_hi": "सिवासागर"},
    {"id": 29, "state_id": 3, "name_en": "Sonitpur", "name_hi": "सोनितपुर"},
    {"id": 30, "state_id": 3, "name_en": "Tinsukia", "name_hi": "टिनसुकिया"},
    {"id": 31, "state_id": 3, "name_en": "Udalguri", "name_hi": "उदलगुड़ी"},
    {
      "id": 32,
      "state_id": 3,
      "name_en": "West Karbi Anglong",
      "name_hi": "पश्चिम कारबी अंगलॉन्ग",
    },
  ];

  static final List<Map<String, dynamic>> biharDistricts = [
    {"id": 1, "state_id": 4, "name_en": "Araria", "name_hi": "अररिया"},
    {"id": 2, "state_id": 4, "name_en": "Arwal", "name_hi": "अरवल"},
    {"id": 3, "state_id": 4, "name_en": "Aurangabad", "name_hi": "औरंगाबाद"},
    {"id": 4, "state_id": 4, "name_en": "Banka", "name_hi": "बांका"},
    {"id": 5, "state_id": 4, "name_en": "Begusarai", "name_hi": "बेगूसराय"},
    {"id": 6, "state_id": 4, "name_en": "Bhagalpur", "name_hi": "भागलपुर"},
    {"id": 7, "state_id": 4, "name_en": "Bhojpur", "name_hi": "भोजपुर"},
    {"id": 8, "state_id": 4, "name_en": "Buxar", "name_hi": "बक्सर"},
    {"id": 9, "state_id": 4, "name_en": "Darbhanga", "name_hi": "दरभंगा"},
    {
      "id": 10,
      "state_id": 4,
      "name_en": "East Champaran",
      "name_hi": "पूर्वी चंपारण",
    },
    {"id": 11, "state_id": 4, "name_en": "Gaya", "name_hi": "गया"},
    {"id": 12, "state_id": 4, "name_en": "Gopalganj", "name_hi": "गोपालगंज"},
    {"id": 13, "state_id": 4, "name_en": "Jamui", "name_hi": "जमुई"},
    {"id": 14, "state_id": 4, "name_en": "Jehanabad", "name_hi": "जहानाबाद"},
    {"id": 15, "state_id": 4, "name_en": "Kaimur", "name_hi": "कैमूर"},
    {"id": 16, "state_id": 4, "name_en": "Katihar", "name_hi": "कठिहार"},
    {"id": 17, "state_id": 4, "name_en": "Khagaria", "name_hi": "खगड़िया"},
    {"id": 18, "state_id": 4, "name_en": "Kishanganj", "name_hi": "किशनगंज"},
    {"id": 19, "state_id": 4, "name_en": "Lakhisarai", "name_hi": "लखीसराय"},
    {"id": 20, "state_id": 4, "name_en": "Madhepura", "name_hi": "मधेपुरा"},
    {"id": 21, "state_id": 4, "name_en": "Madhubani", "name_hi": "मधुबनी"},
    {"id": 22, "state_id": 4, "name_en": "Munger", "name_hi": "मुंगेर"},
    {
      "id": 23,
      "state_id": 4,
      "name_en": "Muzaffarpur",
      "name_hi": "मुजफ्फरपुर",
    },
    {"id": 24, "state_id": 4, "name_en": "Nalanda", "name_hi": "नालंदा"},
    {"id": 25, "state_id": 4, "name_en": "Nawada", "name_hi": "नवादा"},
    {"id": 26, "state_id": 4, "name_en": "Patna", "name_hi": "पटना"},
    {"id": 27, "state_id": 4, "name_en": "Purnia", "name_hi": "पूर्णिया"},
    {"id": 28, "state_id": 4, "name_en": "Rohtas", "name_hi": "रोहतास"},
    {"id": 29, "state_id": 4, "name_en": "Saharsa", "name_hi": "सहरसा"},
    {"id": 30, "state_id": 4, "name_en": "Samastipur", "name_hi": "समस्तीपुर"},
    {"id": 31, "state_id": 4, "name_en": "Saran", "name_hi": "सारण"},
    {"id": 32, "state_id": 4, "name_en": "Sheikhpura", "name_hi": "शेखपुरा"},
    {"id": 33, "state_id": 4, "name_en": "Sheohar", "name_hi": "शिवहर"},
    {"id": 34, "state_id": 4, "name_en": "Sitamarhi", "name_hi": "सीतामढ़ी"},
    {"id": 35, "state_id": 4, "name_en": "Siwan", "name_hi": "सीवान"},
    {"id": 36, "state_id": 4, "name_en": "Supaul", "name_hi": "सुपौल"},
    {"id": 37, "state_id": 4, "name_en": "Vaishali", "name_hi": "वैशाली"},
    {
      "id": 38,
      "state_id": 4,
      "name_en": "West Champaran",
      "name_hi": "पश्चिम चंपारण",
    },
  ];

  static final List<Map<String, dynamic>> chhattisgarhDistricts = [
    {"id": 1, "state_id": 5, "name_en": "Balod", "name_hi": "बलोड"},
    {
      "id": 2,
      "state_id": 5,
      "name_en": "Baloda Bazar",
      "name_hi": "बलौदा बाज़ार",
    },
    {"id": 3, "state_id": 5, "name_en": "Balrampur", "name_hi": "बलरामपुर"},
    {"id": 4, "state_id": 5, "name_en": "Bastar", "name_hi": "बस्तर"},
    {"id": 5, "state_id": 5, "name_en": "Bemetara", "name_hi": "बेमेतरा"},
    {"id": 6, "state_id": 5, "name_en": "Bijapur", "name_hi": "बिजापुर"},
    {"id": 7, "state_id": 5, "name_en": "Bilaspur", "name_hi": "बिलासपुर"},
    {"id": 8, "state_id": 5, "name_en": "Dantewada", "name_hi": "दंतेवाड़ा"},
    {"id": 9, "state_id": 5, "name_en": "Dhamtari", "name_hi": "धमतरी"},
    {"id": 10, "state_id": 5, "name_en": "Durg", "name_hi": "दुर्ग"},
    {"id": 11, "state_id": 5, "name_en": "Gariaband", "name_hi": "गरियाबंद"},
    {
      "id": 12,
      "state_id": 5,
      "name_en": "Janjgir-Champa",
      "name_hi": "जांजगीर-चांपा",
    },
    {"id": 13, "state_id": 5, "name_en": "Jashpur", "name_hi": "जशपुर"},
    {"id": 14, "state_id": 5, "name_en": "Kabirdham", "name_hi": "कबीरधाम"},
    {"id": 15, "state_id": 5, "name_en": "Kanker", "name_hi": "कांकेर"},
    {"id": 16, "state_id": 5, "name_en": "Kondagaon", "name_hi": "कोंडागांव"},
    {"id": 17, "state_id": 5, "name_en": "Korba", "name_hi": "कोरबा"},
    {"id": 18, "state_id": 5, "name_en": "Koriya", "name_hi": "कोरिया"},
    {"id": 19, "state_id": 5, "name_en": "Mahasamund", "name_hi": "महासमुंद"},
    {"id": 20, "state_id": 5, "name_en": "Mungeli", "name_hi": "मुंगेली"},
    {"id": 21, "state_id": 5, "name_en": "Narayanpur", "name_hi": "नारायणपुर"},
    {"id": 22, "state_id": 5, "name_en": "Raigarh", "name_hi": "रायगढ़"},
    {"id": 23, "state_id": 5, "name_en": "Raipur", "name_hi": "रायपुर"},
    {
      "id": 24,
      "state_id": 5,
      "name_en": "Rajnandgaon",
      "name_hi": "राजनंदगांव",
    },
    {"id": 25, "state_id": 5, "name_en": "Sukma", "name_hi": "सुकमा"},
    {"id": 26, "state_id": 5, "name_en": "Surajpur", "name_hi": "सूरजपुर"},
    {"id": 27, "state_id": 5, "name_en": "Surguja", "name_hi": "सुरगुजा"},
  ];

  static final List<Map<String, dynamic>> goaDistricts = [
    {"id": 1, "state_id": 6, "name_en": "North Goa", "name_hi": "उत्तरी गोवा"},
    {"id": 2, "state_id": 6, "name_en": "South Goa", "name_hi": "दक्षिणी गोवा"},
  ];

  static final List<Map<String, dynamic>> gujaratDistricts = [
    {"id": 1, "state_id": 7, "name_en": "Ahmedabad", "name_hi": "अहमदाबाद"},
    {"id": 2, "state_id": 7, "name_en": "Amreli", "name_hi": "अमरेली"},
    {"id": 3, "state_id": 7, "name_en": "Anand", "name_hi": "आनंद"},
    {"id": 4, "state_id": 7, "name_en": "Aravalli", "name_hi": "अरावली"},
    {"id": 5, "state_id": 7, "name_en": "Banaskantha", "name_hi": "बनासकांठा"},
    {"id": 6, "state_id": 7, "name_en": "Bharuch", "name_hi": "भरूच"},
    {"id": 7, "state_id": 7, "name_en": "Bhavnagar", "name_hi": "भावनगर"},
    {"id": 8, "state_id": 7, "name_en": "Botad", "name_hi": "बोटाद"},
    {
      "id": 9,
      "state_id": 7,
      "name_en": "Chhota Udaipur",
      "name_hi": "छोटा उदैपुर",
    },
    {"id": 10, "state_id": 7, "name_en": "Dahod", "name_hi": "दाहोद"},
    {"id": 11, "state_id": 7, "name_en": "Dang", "name_hi": "डांग"},
    {
      "id": 12,
      "state_id": 7,
      "name_en": "Devbhoomi Dwarka",
      "name_hi": "देवभूमि द्वारका",
    },
    {"id": 13, "state_id": 7, "name_en": "Gandhinagar", "name_hi": "गांधीनगर"},
    {
      "id": 14,
      "state_id": 7,
      "name_en": "Gir Somnath",
      "name_hi": "गिर सोमनाथ",
    },
    {"id": 15, "state_id": 7, "name_en": "Jamnagar", "name_hi": "जामनगर"},
    {"id": 16, "state_id": 7, "name_en": "Junagadh", "name_hi": "जूनागढ़"},
    {"id": 17, "state_id": 7, "name_en": "Kheda", "name_hi": "खेडा"},
    {"id": 18, "state_id": 7, "name_en": "Kutch", "name_hi": "कच्छ"},
    {"id": 19, "state_id": 7, "name_en": "Mahisagar", "name_hi": "महीसागर"},
    {"id": 20, "state_id": 7, "name_en": "Mehsana", "name_hi": "महिसाणा"},
    {"id": 21, "state_id": 7, "name_en": "Morbi", "name_hi": "मोरबी"},
    {"id": 22, "state_id": 7, "name_en": "Narmada", "name_hi": "नर्मदा"},
    {"id": 23, "state_id": 7, "name_en": "Navsari", "name_hi": "नवसारी"},
    {"id": 24, "state_id": 7, "name_en": "Panchmahal", "name_hi": "पंचमहल"},
    {"id": 25, "state_id": 7, "name_en": "Patan", "name_hi": "पाटन"},
    {"id": 26, "state_id": 7, "name_en": "Porbandar", "name_hi": "पोरबंदर"},
    {"id": 27, "state_id": 7, "name_en": "Rajkot", "name_hi": "राजकोट"},
    {"id": 28, "state_id": 7, "name_en": "Sabarkantha", "name_hi": "साबरकांठा"},
    {"id": 29, "state_id": 7, "name_en": "Surat", "name_hi": "सूरत"},
    {
      "id": 30,
      "state_id": 7,
      "name_en": "Surendranagar",
      "name_hi": "सुरेंद्रनगर",
    },
    {"id": 31, "state_id": 7, "name_en": "Tapi", "name_hi": "तापी"},
    {"id": 32, "state_id": 7, "name_en": "Vadodara", "name_hi": "वडोदरा"},
    {"id": 33, "state_id": 7, "name_en": "Valsad", "name_hi": "वलसाड"},
  ];

  static final List<Map<String, dynamic>> haryanaDistricts = [
    {"id": 1, "state_id": 8, "name_en": "Ambala", "name_hi": "अम्बाला"},
    {"id": 2, "state_id": 8, "name_en": "Bhiwani", "name_hi": "भिवानी"},
    {
      "id": 3,
      "state_id": 8,
      "name_en": "Charkhi Dadri",
      "name_hi": "चरखी दादरी",
    },
    {"id": 4, "state_id": 8, "name_en": "Faridabad", "name_hi": "फरीदाबाद"},
    {"id": 5, "state_id": 8, "name_en": "Fatehabad", "name_hi": "फतेहाबाद"},
    {"id": 6, "state_id": 8, "name_en": "Gurugram", "name_hi": "गुरुग्राम"},
    {"id": 7, "state_id": 8, "name_en": "Hisar", "name_hi": "हिसार"},
    {"id": 8, "state_id": 8, "name_en": "Jhajjar", "name_hi": "झज्जर"},
    {"id": 9, "state_id": 8, "name_en": "Jind", "name_hi": "जिन्द"},
    {"id": 10, "state_id": 8, "name_en": "Kaithal", "name_hi": "कैथल"},
    {"id": 11, "state_id": 8, "name_en": "Karnal", "name_hi": "करनाल"},
    {
      "id": 12,
      "state_id": 8,
      "name_en": "Kurukshetra",
      "name_hi": "कुरुक्षेत्र",
    },
    {
      "id": 13,
      "state_id": 8,
      "name_en": "Mahendragarh",
      "name_hi": "महेंद्रगढ़",
    },
    {
      "id": 14,
      "state_id": 8,
      "name_en": "Mewat (Nuh)",
      "name_hi": "मेवात (नूह)",
    },
    {"id": 15, "state_id": 8, "name_en": "Palwal", "name_hi": "पालवल"},
    {"id": 16, "state_id": 8, "name_en": "Panchkula", "name_hi": "पंचकुला"},
    {"id": 17, "state_id": 8, "name_en": "Panipat", "name_hi": "पानीपत"},
    {"id": 18, "state_id": 8, "name_en": "Rewari", "name_hi": "रेवाड़ी"},
    {"id": 19, "state_id": 8, "name_en": "Rohtak", "name_hi": "रोहतक"},
    {"id": 20, "state_id": 8, "name_en": "Sirsa", "name_hi": "सिरसा"},
    {"id": 21, "state_id": 8, "name_en": "Sonipat", "name_hi": "सोनीपत"},
    {"id": 22, "state_id": 8, "name_en": "Yamunanagar", "name_hi": "यमुनानगर"},
  ];

  static final List<Map<String, dynamic>> himachalPradeshDistricts = [
    {"id": 1, "state_id": 9, "name_en": "Bilaspur", "name_hi": "बिलासपुर"},
    {"id": 2, "state_id": 9, "name_en": "Chamba", "name_hi": "चंबा"},
    {"id": 3, "state_id": 9, "name_en": "Hamirpur", "name_hi": "हमीरपुर"},
    {"id": 4, "state_id": 9, "name_en": "Kangra", "name_hi": "कांगड़ा"},
    {"id": 5, "state_id": 9, "name_en": "Kinnaur", "name_hi": "किन्नौर"},
    {"id": 6, "state_id": 9, "name_en": "Kullu", "name_hi": "कुल्लू"},
    {
      "id": 7,
      "state_id": 9,
      "name_en": "Lahaul and Spiti",
      "name_hi": "लाहुल और स्पीति",
    },
    {"id": 8, "state_id": 9, "name_en": "Mandi", "name_hi": "मंडी"},
    {"id": 9, "state_id": 9, "name_en": "Shimla", "name_hi": "शिमला"},
    {"id": 10, "state_id": 9, "name_en": "Sirmaur", "name_hi": "सिरमौर"},
    {"id": 11, "state_id": 9, "name_en": "Solan", "name_hi": "सोलन"},
    {"id": 12, "state_id": 9, "name_en": "Una", "name_hi": "ऊना"},
  ];

  static final List<Map<String, dynamic>> jharkhandDistricts = [
    {"id": 1, "state_id": 10, "name_en": "Bokaro", "name_hi": "बोकारो"},
    {"id": 2, "state_id": 10, "name_en": "Chatra", "name_hi": "चतरा"},
    {"id": 3, "state_id": 10, "name_en": "Deoghar", "name_hi": "देवघर"},
    {"id": 4, "state_id": 10, "name_en": "Dhanbad", "name_hi": "धनबाद"},
    {"id": 5, "state_id": 10, "name_en": "Dumka", "name_hi": "दुमका"},
    {
      "id": 6,
      "state_id": 10,
      "name_en": "East Singhbhum",
      "name_hi": "पूर्वी सिंहभूम",
    },
    {"id": 7, "state_id": 10, "name_en": "Garhwa", "name_hi": "गढ़वा"},
    {"id": 8, "state_id": 10, "name_en": "Giridih", "name_hi": "गिरीडीह"},
    {"id": 9, "state_id": 10, "name_en": "Godda", "name_hi": "गोड्डा"},
    {"id": 10, "state_id": 10, "name_en": "Gumla", "name_hi": "गुमला"},
    {"id": 11, "state_id": 10, "name_en": "Hazaribagh", "name_hi": "हज़ारीबाग"},
    {"id": 12, "state_id": 10, "name_en": "Jamtara", "name_hi": "जम्तारा"},
    {"id": 13, "state_id": 10, "name_en": "Khunti", "name_hi": "खूंटी"},
    {"id": 14, "state_id": 10, "name_en": "Koderma", "name_hi": "कोडरमा"},
    {"id": 15, "state_id": 10, "name_en": "Latehar", "name_hi": "लेटेहार"},
    {"id": 16, "state_id": 10, "name_en": "Lohardaga", "name_hi": "लोहरदगा"},
    {"id": 17, "state_id": 10, "name_en": "Pakur", "name_hi": "पाकुर"},
    {"id": 18, "state_id": 10, "name_en": "Palamu", "name_hi": "पलामू"},
    {"id": 19, "state_id": 10, "name_en": "Ramgarh", "name_hi": "रामगढ़"},
    {"id": 20, "state_id": 10, "name_en": "Ranchi", "name_hi": "रांची"},
    {"id": 21, "state_id": 10, "name_en": "Sahibganj", "name_hi": "साहिबगंज"},
    {
      "id": 22,
      "state_id": 10,
      "name_en": "Seraikela Kharsawan",
      "name_hi": "सेरायकेला खरसावां",
    },
    {"id": 23, "state_id": 10, "name_en": "Simdega", "name_hi": "सिमडेगा"},
    {
      "id": 24,
      "state_id": 10,
      "name_en": "West Singhbhum",
      "name_hi": "पश्चिमी सिंहभूम",
    },
  ];

  static final List<Map<String, dynamic>> karnatakaDistricts = [
    {"id": 1, "state_id": 11, "name_en": "Bagalkot", "name_hi": "बागलकोट"},
    {
      "id": 2,
      "state_id": 11,
      "name_en": "Bangalore Rural",
      "name_hi": "बेंगलुरु ग्रामीण",
    },
    {
      "id": 3,
      "state_id": 11,
      "name_en": "Bangalore Urban",
      "name_hi": "बेंगलुरु शहरी",
    },
    {"id": 4, "state_id": 11, "name_en": "Belagavi", "name_hi": "बेलगावी"},
    {"id": 5, "state_id": 11, "name_en": "Bellary", "name_hi": "बेल्लारी"},
    {"id": 6, "state_id": 11, "name_en": "Bidar", "name_hi": "बिदर"},
    {
      "id": 7,
      "state_id": 11,
      "name_en": "Chamarajanagar",
      "name_hi": "चामराजनगर",
    },
    {
      "id": 8,
      "state_id": 11,
      "name_en": "Chikballapur",
      "name_hi": "चिकबल्लापुर",
    },
    {
      "id": 9,
      "state_id": 11,
      "name_en": "Chikkamagaluru",
      "name_hi": "चिक्कमंगलुरु",
    },
    {
      "id": 10,
      "state_id": 11,
      "name_en": "Chitradurga",
      "name_hi": "चित्रदुर्ग",
    },
    {
      "id": 11,
      "state_id": 11,
      "name_en": "Dakshina Kannada",
      "name_hi": "दक्षिण कन्नड़",
    },
    {"id": 12, "state_id": 11, "name_en": "Davanagere", "name_hi": "दावणगेरे"},
    {"id": 13, "state_id": 11, "name_en": "Dharwad", "name_hi": "धारवाड़"},
    {"id": 14, "state_id": 11, "name_en": "Gadag", "name_hi": "गदग"},
    {"id": 15, "state_id": 11, "name_en": "Hassan", "name_hi": "हसन"},
    {"id": 16, "state_id": 11, "name_en": "Haveri", "name_hi": "हावेरी"},
    {"id": 17, "state_id": 11, "name_en": "Kodagu", "name_hi": "कोडागु"},
    {"id": 18, "state_id": 11, "name_en": "Kolar", "name_hi": "कोलार"},
    {"id": 19, "state_id": 11, "name_en": "Koppal", "name_hi": "कोप्पल"},
    {"id": 20, "state_id": 11, "name_en": "Mandya", "name_hi": "मंड्या"},
    {"id": 21, "state_id": 11, "name_en": "Mysuru", "name_hi": "मैसूरु"},
    {"id": 22, "state_id": 11, "name_en": "Raichur", "name_hi": "रायचूर"},
    {"id": 23, "state_id": 11, "name_en": "Ramanagara", "name_hi": "रमणगरा"},
    {"id": 24, "state_id": 11, "name_en": "Shivamogga", "name_hi": "शिवमोगा"},
    {"id": 25, "state_id": 11, "name_en": "Tumakuru", "name_hi": "तुमकुरु"},
    {"id": 26, "state_id": 11, "name_en": "Udupi", "name_hi": "उडुपी"},
    {
      "id": 27,
      "state_id": 11,
      "name_en": "Uttara Kannada",
      "name_hi": "उत्तर कन्नड़",
    },
    {"id": 28, "state_id": 11, "name_en": "Vijayapura", "name_hi": "विजयपुर"},
    {"id": 29, "state_id": 11, "name_en": "Yadgir", "name_hi": "यादगीर"},
  ];

  static final List<Map<String, dynamic>> keralaDistricts = [
    {"id": 1, "state_id": 12, "name_en": "Alappuzha", "name_hi": "अलप्पुझा"},
    {"id": 2, "state_id": 12, "name_en": "Ernakulam", "name_hi": "एर्नाकुलम"},
    {"id": 3, "state_id": 12, "name_en": "Idukki", "name_hi": "इडुक्की"},
    {"id": 4, "state_id": 12, "name_en": "Kannur", "name_hi": "कन्नूर"},
    {"id": 5, "state_id": 12, "name_en": "Kasaragod", "name_hi": "कसारगोड"},
    {"id": 6, "state_id": 12, "name_en": "Kollam", "name_hi": "कोल्लम"},
    {"id": 7, "state_id": 12, "name_en": "Kottayam", "name_hi": "कोट्टायम"},
    {"id": 8, "state_id": 12, "name_en": "Kozhikode", "name_hi": "कोझिकोड"},
    {"id": 9, "state_id": 12, "name_en": "Malappuram", "name_hi": "मलप्पुरम"},
    {"id": 10, "state_id": 12, "name_en": "Palakkad", "name_hi": "पलक्कड़"},
    {
      "id": 11,
      "state_id": 12,
      "name_en": "Pathanamthitta",
      "name_hi": "पथानमथिट्टा",
    },
    {
      "id": 12,
      "state_id": 12,
      "name_en": "Thiruvananthapuram",
      "name_hi": "तिरुवनंतपुरम",
    },
    {"id": 13, "state_id": 12, "name_en": "Thrissur", "name_hi": "त्रिशुर"},
    {"id": 14, "state_id": 12, "name_en": "Wayanad", "name_hi": "वायनाड"},
  ];

  static final List<Map<String, dynamic>> madhyaPradeshDistricts = [
    {"id": 1, "state_id": 13, "name_en": "Agar Malwa", "name_hi": "आगर मलवा"},
    {"id": 2, "state_id": 13, "name_en": "Alirajpur", "name_hi": "अलीराजपुर"},
    {"id": 3, "state_id": 13, "name_en": "Anuppur", "name_hi": "अनूपपुर"},
    {"id": 4, "state_id": 13, "name_en": "Ashoknagar", "name_hi": "अशोकनगर"},
    {"id": 5, "state_id": 13, "name_en": "Balaghat", "name_hi": "बालाघाट"},
    {"id": 6, "state_id": 13, "name_en": "Barwani", "name_hi": "बरवानी"},
    {"id": 7, "state_id": 13, "name_en": "Betul", "name_hi": "बेतुल"},
    {"id": 8, "state_id": 13, "name_en": "Bhind", "name_hi": "भींद"},
    {"id": 9, "state_id": 13, "name_en": "Bhopal", "name_hi": "भोपाल"},
    {"id": 10, "state_id": 13, "name_en": "Burhanpur", "name_hi": "बुरहानपुर"},
    {"id": 11, "state_id": 13, "name_en": "Chhatarpur", "name_hi": "छतरपुर"},
    {"id": 12, "state_id": 13, "name_en": "Chhindwara", "name_hi": "छिंदवाड़ा"},
    {"id": 13, "state_id": 13, "name_en": "Damoh", "name_hi": "दमोह"},
    {"id": 14, "state_id": 13, "name_en": "Datia", "name_hi": "दतिया"},
    {"id": 15, "state_id": 13, "name_en": "Dewas", "name_hi": "देवास"},
    {"id": 16, "state_id": 13, "name_en": "Dhar", "name_hi": "धार"},
    {"id": 17, "state_id": 13, "name_en": "Dindori", "name_hi": "डिंडोरी"},
    {"id": 18, "state_id": 13, "name_en": "Guna", "name_hi": "गुना"},
    {"id": 19, "state_id": 13, "name_en": "Gwalior", "name_hi": "ग्वालियर"},
    {"id": 20, "state_id": 13, "name_en": "Harda", "name_hi": "हरदा"},
    {
      "id": 21,
      "state_id": 13,
      "name_en": "Hoshangabad",
      "name_hi": "होशंगाबाद",
    },
    {"id": 22, "state_id": 13, "name_en": "Indore", "name_hi": "इंदौर"},
    {"id": 23, "state_id": 13, "name_en": "Jabalpur", "name_hi": "जबलपुर"},
    {"id": 24, "state_id": 13, "name_en": "Jhabua", "name_hi": "झाबुआ"},
    {"id": 25, "state_id": 13, "name_en": "Katni", "name_hi": "कटनी"},
    {"id": 26, "state_id": 13, "name_en": "Khandwa", "name_hi": "खंडवा"},
    {"id": 27, "state_id": 13, "name_en": "Khargone", "name_hi": "खरगोन"},
    {"id": 28, "state_id": 13, "name_en": "Mandla", "name_hi": "मंडला"},
    {"id": 29, "state_id": 13, "name_en": "Mandsaur", "name_hi": "मंदसौर"},
    {"id": 30, "state_id": 13, "name_en": "Morena", "name_hi": "मुरैना"},
    {
      "id": 31,
      "state_id": 13,
      "name_en": "Narsinghpur",
      "name_hi": "नरसिंहपुर",
    },
    {"id": 32, "state_id": 13, "name_en": "Neemuch", "name_hi": "नीमच"},
    {"id": 33, "state_id": 13, "name_en": "Panna", "name_hi": "पन्ना"},
    {"id": 34, "state_id": 13, "name_en": "Raisen", "name_hi": "रायसेन"},
    {"id": 35, "state_id": 13, "name_en": "Rajgarh", "name_hi": "राजगढ़"},
    {"id": 36, "state_id": 13, "name_en": "Ratlam", "name_hi": "रतलाम"},
    {"id": 37, "state_id": 13, "name_en": "Rewa", "name_hi": "रीवा"},
    {"id": 38, "state_id": 13, "name_en": "Sagar", "name_hi": "सागर"},
    {"id": 39, "state_id": 13, "name_en": "Satna", "name_hi": "सतना"},
    {"id": 40, "state_id": 13, "name_en": "Sehore", "name_hi": "सेहोर"},
    {"id": 41, "state_id": 13, "name_en": "Seoni", "name_hi": "सेओनी"},
    {"id": 42, "state_id": 13, "name_en": "Shahdol", "name_hi": "शहडोल"},
    {"id": 43, "state_id": 13, "name_en": "Shajapur", "name_hi": "शाजापुर"},
    {"id": 44, "state_id": 13, "name_en": "Sheopur", "name_hi": "श्योपुर"},
    {"id": 45, "state_id": 13, "name_en": "Shivpuri", "name_hi": "शिवपुरी"},
    {"id": 46, "state_id": 13, "name_en": "Sidhi", "name_hi": "सिंधी"},
    {"id": 47, "state_id": 13, "name_en": "Singrauli", "name_hi": "सिंगरौली"},
    {"id": 48, "state_id": 13, "name_en": "Tikamgarh", "name_hi": "टिकामगढ़"},
    {"id": 49, "state_id": 13, "name_en": "Ujjain", "name_hi": "उज्जैन"},
    {"id": 50, "state_id": 13, "name_en": "Umaria", "name_hi": "उमरिया"},
    {"id": 51, "state_id": 13, "name_en": "Vidisha", "name_hi": "विदिशा"},
  ];

  static final List<Map<String, dynamic>> maharashtraDistricts = [
    {"id": 1, "state_id": 14, "name_en": "Ahmednagar", "name_hi": "अहमदनगर"},
    {"id": 2, "state_id": 14, "name_en": "Akola", "name_hi": "अकोला"},
    {"id": 3, "state_id": 14, "name_en": "Amravati", "name_hi": "अमरावती"},
    {"id": 4, "state_id": 14, "name_en": "Aurangabad", "name_hi": "औरंगाबाद"},
    {"id": 5, "state_id": 14, "name_en": "Beed", "name_hi": "बीड"},
    {"id": 6, "state_id": 14, "name_en": "Bhandara", "name_hi": "भंडारा"},
    {"id": 7, "state_id": 14, "name_en": "Buldhana", "name_hi": "बुलढाणा"},
    {"id": 8, "state_id": 14, "name_en": "Chandrapur", "name_hi": "चंद्रपुर"},
    {"id": 9, "state_id": 14, "name_en": "Dhule", "name_hi": "धुळे"},
    {"id": 10, "state_id": 14, "name_en": "Gadchiroli", "name_hi": "गडचिरोली"},
    {"id": 11, "state_id": 14, "name_en": "Gondia", "name_hi": "गोंदिया"},
    {"id": 12, "state_id": 14, "name_en": "Hingoli", "name_hi": "हिंगोली"},
    {"id": 13, "state_id": 14, "name_en": "Jalgaon", "name_hi": "जळगांव"},
    {"id": 14, "state_id": 14, "name_en": "Jalna", "name_hi": "जालना"},
    {"id": 15, "state_id": 14, "name_en": "Kolhapur", "name_hi": "कोल्हापूर"},
    {"id": 16, "state_id": 14, "name_en": "Latur", "name_hi": "लातूर"},
    {
      "id": 17,
      "state_id": 14,
      "name_en": "Mumbai City",
      "name_hi": "मुंबई शहर",
    },
    {
      "id": 18,
      "state_id": 14,
      "name_en": "Mumbai Suburban",
      "name_hi": "मुंबई उपनगरीय",
    },
    {"id": 19, "state_id": 14, "name_en": "Nagpur", "name_hi": "नागपुर"},
    {"id": 20, "state_id": 14, "name_en": "Nanded", "name_hi": "नांदेड"},
    {"id": 21, "state_id": 14, "name_en": "Nandurbar", "name_hi": "नंदुरबार"},
    {"id": 22, "state_id": 14, "name_en": "Nashik", "name_hi": "नाशिक"},
    {"id": 23, "state_id": 14, "name_en": "Osmanabad", "name_hi": "उस्मानाबाद"},
    {"id": 24, "state_id": 14, "name_en": "Palghar", "name_hi": "पालघर"},
    {"id": 25, "state_id": 14, "name_en": "Parbhani", "name_hi": "परभणी"},
    {"id": 26, "state_id": 14, "name_en": "Pune", "name_hi": "पुणे"},
    {"id": 27, "state_id": 14, "name_en": "Raigad", "name_hi": "रायगड"},
    {"id": 28, "state_id": 14, "name_en": "Ratnagiri", "name_hi": "रत्नागिरी"},
    {"id": 29, "state_id": 14, "name_en": "Sangli", "name_hi": "सांगली"},
    {"id": 30, "state_id": 14, "name_en": "Satara", "name_hi": "सतारा"},
    {
      "id": 31,
      "state_id": 14,
      "name_en": "Sindhudurg",
      "name_hi": "सिंधुदुर्ग",
    },
    {"id": 32, "state_id": 14, "name_en": "Solapur", "name_hi": "सोलापुर"},
    {"id": 33, "state_id": 14, "name_en": "Thane", "name_hi": "ठाणे"},
    {"id": 34, "state_id": 14, "name_en": "Wardha", "name_hi": "वर्धा"},
    {"id": 35, "state_id": 14, "name_en": "Washim", "name_hi": "वाशिम"},
    {"id": 36, "state_id": 14, "name_en": "Yavatmal", "name_hi": "यवतमाल"},
  ];

  static final List<Map<String, dynamic>> manipurDistricts = [
    {"id": 1, "state_id": 15, "name_en": "Bishnupur", "name_hi": "बिश्नुपुर"},
    {"id": 2, "state_id": 15, "name_en": "Chandel", "name_hi": "चांदेळ"},
    {
      "id": 3,
      "state_id": 15,
      "name_en": "Churachandpur",
      "name_hi": "चुराचांदपुर",
    },
    {
      "id": 4,
      "state_id": 15,
      "name_en": "Imphal East",
      "name_hi": "इंफाल पूर्वी",
    },
    {
      "id": 5,
      "state_id": 15,
      "name_en": "Imphal West",
      "name_hi": "इंफाल पश्चिम",
    },
    {"id": 6, "state_id": 15, "name_en": "Jiribam", "name_hi": "जिरिबम"},
    {"id": 7, "state_id": 15, "name_en": "Kakching", "name_hi": "काकचिंग"},
    {"id": 8, "state_id": 15, "name_en": "Kamjong", "name_hi": "कामजोंग"},
    {"id": 9, "state_id": 15, "name_en": "Kangpokpi", "name_hi": "कांगपोम्पी"},
    {"id": 10, "state_id": 15, "name_en": "Noney", "name_hi": "नोनी"},
    {"id": 11, "state_id": 15, "name_en": "Pherzawl", "name_hi": "फेरजावल"},
    {"id": 12, "state_id": 15, "name_en": "Senapati", "name_hi": "सेनापति"},
    {
      "id": 13,
      "state_id": 15,
      "name_en": "Tamenglong",
      "name_hi": "तामेंगलॉन्ग",
    },
    {
      "id": 14,
      "state_id": 15,
      "name_en": "Tengnoupal",
      "name_hi": "तेंग्नूपाल",
    },
    {"id": 15, "state_id": 15, "name_en": "Thoubal", "name_hi": "थौबाल"},
    {"id": 16, "state_id": 15, "name_en": "Ukhrul", "name_hi": "उखरुल"},
  ];

  static final List<Map<String, dynamic>> meghalayaDistricts = [
    {
      "id": 1,
      "state_id": 16,
      "name_en": "East Garo Hills",
      "name_hi": "पूर्वी गारो हिल्स",
    },
    {
      "id": 2,
      "state_id": 16,
      "name_en": "East Jaintia Hills",
      "name_hi": "पूर्वी जैंटिया हिल्स",
    },
    {
      "id": 3,
      "state_id": 16,
      "name_en": "East Khasi Hills",
      "name_hi": "पूर्वी खासी हिल्स",
    },
    {
      "id": 4,
      "state_id": 16,
      "name_en": "North Garo Hills",
      "name_hi": "उत्तर गारो हिल्स",
    },
    {"id": 5, "state_id": 16, "name_en": "Ri Bhoi", "name_hi": "री भोई"},
    {
      "id": 6,
      "state_id": 16,
      "name_en": "South Garo Hills",
      "name_hi": "दक्षिण गारो हिल्स",
    },
    {
      "id": 7,
      "state_id": 16,
      "name_en": "South West Garo Hills",
      "name_hi": "दक्षिण पश्चिम गारो हिल्स",
    },
    {
      "id": 8,
      "state_id": 16,
      "name_en": "South West Khasi Hills",
      "name_hi": "दक्षिण पश्चिम खासी हिल्स",
    },
    {
      "id": 9,
      "state_id": 16,
      "name_en": "West Garo Hills",
      "name_hi": "पश्चिम गारो हिल्स",
    },
    {
      "id": 10,
      "state_id": 16,
      "name_en": "West Jaintia Hills",
      "name_hi": "पश्चिम जैंटिया हिल्स",
    },
    {
      "id": 11,
      "state_id": 16,
      "name_en": "West Khasi Hills",
      "name_hi": "पश्चिम खासी हिल्स",
    },
  ];

  static final List<Map<String, dynamic>> mizoramDistricts = [
    {"id": 1, "state_id": 17, "name_en": "Aizawl", "name_hi": "ऐज़ॉल"},
    {"id": 2, "state_id": 17, "name_en": "Champhai", "name_hi": "चाम्फाई"},
    {"id": 3, "state_id": 17, "name_en": "Kolasib", "name_hi": "कोलासिब"},
    {"id": 4, "state_id": 17, "name_en": "Lawngtlai", "name_hi": "लॉन्गतलाई"},
    {"id": 5, "state_id": 17, "name_en": "Lunglei", "name_hi": "लुंगलेई"},
    {"id": 6, "state_id": 17, "name_en": "Mamit", "name_hi": "ममित"},
    {"id": 7, "state_id": 17, "name_en": "Saiha", "name_hi": "साइहा"},
    {"id": 8, "state_id": 17, "name_en": "Serchhip", "name_hi": "सर्चिप"},
  ];

  static final List<Map<String, dynamic>> nagalandDistricts = [
    {"id": 1, "state_id": 18, "name_en": "Dimapur", "name_hi": "डिमापुर"},
    {"id": 2, "state_id": 18, "name_en": "Kiphire", "name_hi": "किफ़िरे"},
    {"id": 3, "state_id": 18, "name_en": "Kohima", "name_hi": "कोहिमा"},
    {"id": 4, "state_id": 18, "name_en": "Longleng", "name_hi": "लॉन्गलेंग"},
    {"id": 5, "state_id": 18, "name_en": "Mokokchung", "name_hi": "मोकोकचुंग"},
    {"id": 6, "state_id": 18, "name_en": "Mon", "name_hi": "मॉन"},
    {"id": 7, "state_id": 18, "name_en": "Peren", "name_hi": "पेरन"},
    {"id": 8, "state_id": 18, "name_en": "Phek", "name_hi": "फेक"},
    {"id": 9, "state_id": 18, "name_en": "Tuensang", "name_hi": "टुएंसांग"},
    {"id": 10, "state_id": 18, "name_en": "Wokha", "name_hi": "वोक्हा"},
    {"id": 11, "state_id": 18, "name_en": "Zunheboto", "name_hi": "जुन्हेबोटो"},
  ];

  static final List<Map<String, dynamic>> odishaDistricts = [
    {"id": 1, "state_id": 19, "name_en": "Angul", "name_hi": "अंगुल"},
    {"id": 2, "state_id": 19, "name_en": "Balangir", "name_hi": "बलांगीर"},
    {"id": 3, "state_id": 19, "name_en": "Balasore", "name_hi": "बालासोर"},
    {"id": 4, "state_id": 19, "name_en": "Bargarh", "name_hi": "बारगढ़"},
    {"id": 5, "state_id": 19, "name_en": "Bhadrak", "name_hi": "भद्रक"},
    {"id": 6, "state_id": 19, "name_en": "Boudh", "name_hi": "बौध"},
    {"id": 7, "state_id": 19, "name_en": "Cuttack", "name_hi": "कटक"},
    {"id": 8, "state_id": 19, "name_en": "Deogarh", "name_hi": "देवगढ़"},
    {"id": 9, "state_id": 19, "name_en": "Dhenkanal", "name_hi": "ढेंकानाल"},
    {"id": 10, "state_id": 19, "name_en": "Gajapati", "name_hi": "गजपति"},
    {"id": 11, "state_id": 19, "name_en": "Ganjam", "name_hi": "गंजाम"},
    {
      "id": 12,
      "state_id": 19,
      "name_en": "Jagatsinghpur",
      "name_hi": "जगतसिंहपुर",
    },
    {"id": 13, "state_id": 19, "name_en": "Jajpur", "name_hi": "जाजपुर"},
    {
      "id": 14,
      "state_id": 19,
      "name_en": "Jharsuguda",
      "name_hi": "झारसुगुड़ा",
    },
    {"id": 15, "state_id": 19, "name_en": "Kalahandi", "name_hi": "कालाहांडी"},
    {"id": 16, "state_id": 19, "name_en": "Kandhamal", "name_hi": "कंधमाल"},
    {
      "id": 17,
      "state_id": 19,
      "name_en": "Kendrapara",
      "name_hi": "केंदारपारा",
    },
    {"id": 18, "state_id": 19, "name_en": "Kendujhar", "name_hi": "केन्दुझर"},
    {"id": 19, "state_id": 19, "name_en": "Khordha", "name_hi": "खोर्धा"},
    {"id": 20, "state_id": 19, "name_en": "Koraput", "name_hi": "कोरापुट"},
    {
      "id": 21,
      "state_id": 19,
      "name_en": "Malkangiri",
      "name_hi": "मल्कांगिरी",
    },
    {"id": 22, "state_id": 19, "name_en": "Mayurbhanj", "name_hi": "मयूरभंज"},
    {"id": 23, "state_id": 19, "name_en": "Nabarangpur", "name_hi": "नबरंगपुर"},
    {"id": 24, "state_id": 19, "name_en": "Nuapada", "name_hi": "नुआपड़ा"},
    {"id": 25, "state_id": 19, "name_en": "Puri", "name_hi": "पुरी"},
    {"id": 26, "state_id": 19, "name_en": "Rayagada", "name_hi": "रायगड़ा"},
    {"id": 27, "state_id": 19, "name_en": "Sambalpur", "name_hi": "संभलपुर"},
    {"id": 28, "state_id": 19, "name_en": "Sonepur", "name_hi": "सोनपुर"},
    {"id": 29, "state_id": 19, "name_en": "Sundargarh", "name_hi": "सुंदरगढ़"},
  ];

  static final List<Map<String, dynamic>> punjabDistricts = [
    {"id": 1, "state_id": 20, "name_en": "Amritsar", "name_hi": "अमृतसर"},
    {"id": 2, "state_id": 20, "name_en": "Barnala", "name_hi": "बरनाला"},
    {"id": 3, "state_id": 20, "name_en": "Bathinda", "name_hi": "बठिंडा"},
    {"id": 4, "state_id": 20, "name_en": "Faridkot", "name_hi": "फरीदकोट"},
    {
      "id": 5,
      "state_id": 20,
      "name_en": "Fatehgarh Sahib",
      "name_hi": "फतेहगढ़ साहिब",
    },
    {"id": 6, "state_id": 20, "name_en": "Fazilka", "name_hi": "फाजिल्का"},
    {"id": 7, "state_id": 20, "name_en": "Ferozepur", "name_hi": "फिरोज़पुर"},
    {"id": 8, "state_id": 20, "name_en": "Gurdaspur", "name_hi": "गुरदासपुर"},
    {"id": 9, "state_id": 20, "name_en": "Hoshiarpur", "name_hi": "होशियारपुर"},
    {"id": 10, "state_id": 20, "name_en": "Jalandhar", "name_hi": "जालंधर"},
    {"id": 11, "state_id": 20, "name_en": "Kapurthala", "name_hi": "कपूरथला"},
    {"id": 12, "state_id": 20, "name_en": "Ludhiana", "name_hi": "लुधियाना"},
    {"id": 13, "state_id": 20, "name_en": "Mansa", "name_hi": "मानसा"},
    {"id": 14, "state_id": 20, "name_en": "Moga", "name_hi": "मोगा"},
    {"id": 15, "state_id": 20, "name_en": "Muktsar", "name_hi": "मुख्तसर"},
    {
      "id": 16,
      "state_id": 20,
      "name_en": "Nawanshahr (Shahid Bhagat Singh Nagar)",
      "name_hi": "नवांशहर (शहीद भगत सिंह नगर)",
    },
    {"id": 17, "state_id": 20, "name_en": "Pathankot", "name_hi": "पठानकोट"},
    {"id": 18, "state_id": 20, "name_en": "Patiala", "name_hi": "पटियाला"},
    {"id": 19, "state_id": 20, "name_en": "Rupnagar", "name_hi": "रुपनगर"},
    {
      "id": 20,
      "state_id": 20,
      "name_en": "S.A.S. Nagar",
      "name_hi": "एस.ए.एस. नगर",
    },
    {"id": 21, "state_id": 20, "name_en": "Sangrur", "name_hi": "संगरूर"},
    {"id": 22, "state_id": 20, "name_en": "Tarn Taran", "name_hi": "तरण तारण"},
  ];

  static final List<Map<String, dynamic>> rajasthanDistricts = [
    {"id": 1, "state_id": 21, "name_en": "Ajmer", "name_hi": "अजमेर"},
    {"id": 2, "state_id": 21, "name_en": "Alwar", "name_hi": "अलवर"},
    {"id": 3, "state_id": 21, "name_en": "Banswara", "name_hi": "बांसवाड़ा"},
    {"id": 4, "state_id": 21, "name_en": "Baran", "name_hi": "बारां"},
    {"id": 5, "state_id": 21, "name_en": "Barmer", "name_hi": "बाड़मेर"},
    {"id": 6, "state_id": 21, "name_en": "Bharatpur", "name_hi": "भरतपुर"},
    {"id": 7, "state_id": 21, "name_en": "Bhilwara", "name_hi": "भीलवाड़ा"},
    {"id": 8, "state_id": 21, "name_en": "Bikaner", "name_hi": "बीकानेर"},
    {"id": 9, "state_id": 21, "name_en": "Bundi", "name_hi": "बूंदी"},
    {
      "id": 10,
      "state_id": 21,
      "name_en": "Chittorgarh",
      "name_hi": "चित्तौड़गढ़",
    },
    {"id": 11, "state_id": 21, "name_en": "Churu", "name_hi": "चुरु"},
    {"id": 12, "state_id": 21, "name_en": "Dausa", "name_hi": "दौसा"},
    {"id": 13, "state_id": 21, "name_en": "Dholpur", "name_hi": "धौलपुर"},
    {"id": 14, "state_id": 21, "name_en": "Dungarpur", "name_hi": "डूंगरपुर"},
    {
      "id": 15,
      "state_id": 21,
      "name_en": "Hanumangarh",
      "name_hi": "हनुमानगढ़",
    },
    {"id": 16, "state_id": 21, "name_en": "Jaipur", "name_hi": "जयपुर"},
    {"id": 17, "state_id": 21, "name_en": "Jaisalmer", "name_hi": "जैसलमेर"},
    {"id": 18, "state_id": 21, "name_en": "Jalore", "name_hi": "जालोर"},
    {"id": 19, "state_id": 21, "name_en": "Jhalawar", "name_hi": "झालावाड़"},
    {"id": 20, "state_id": 21, "name_en": "Jhunjhunu", "name_hi": "झुंझुनू"},
    {"id": 21, "state_id": 21, "name_en": "Jodhpur", "name_hi": "जोधपुर"},
    {"id": 22, "state_id": 21, "name_en": "Karauli", "name_hi": "करौली"},
    {"id": 23, "state_id": 21, "name_en": "Kota", "name_hi": "कोटा"},
    {"id": 24, "state_id": 21, "name_en": "Nagaur", "name_hi": "नागौर"},
    {"id": 25, "state_id": 21, "name_en": "Pali", "name_hi": "पाली"},
    {"id": 26, "state_id": 21, "name_en": "Pratapgarh", "name_hi": "प्रतापगढ़"},
    {"id": 27, "state_id": 21, "name_en": "Rajsamand", "name_hi": "राजसमंद"},
    {
      "id": 28,
      "state_id": 21,
      "name_en": "Sawai Madhopur",
      "name_hi": "सवाई माधोपुर",
    },
    {"id": 29, "state_id": 21, "name_en": "Sikar", "name_hi": "सीकर"},
    {"id": 30, "state_id": 21, "name_en": "Sirohi", "name_hi": "सिरोही"},
    {"id": 31, "state_id": 21, "name_en": "Tonk", "name_hi": "टोंक"},
    {"id": 32, "state_id": 21, "name_en": "Udaipur", "name_hi": "उदयपुर"},
  ];

  static final List<Map<String, dynamic>> sikkimDistricts = [
    {
      "id": 1,
      "state_id": 22,
      "name_en": "East Sikkim",
      "name_hi": "पूर्व सिक्किम",
    },
    {
      "id": 2,
      "state_id": 22,
      "name_en": "North Sikkim",
      "name_hi": "उत्तर सिक्किम",
    },
    {
      "id": 3,
      "state_id": 22,
      "name_en": "South Sikkim",
      "name_hi": "दक्षिण सिक्किम",
    },
    {
      "id": 4,
      "state_id": 22,
      "name_en": "West Sikkim",
      "name_hi": "पश्चिम सिक्किम",
    },
  ];

  static final List<Map<String, dynamic>> tamilNaduDistricts = [
    {"id": 1, "state_id": 23, "name_en": "Ariyalur", "name_hi": "अरियालुर"},
    {
      "id": 2,
      "state_id": 23,
      "name_en": "Chengalpattu",
      "name_hi": "चेंगलपट्टु",
    },
    {"id": 3, "state_id": 23, "name_en": "Chennai", "name_hi": "चेन्नई"},
    {"id": 4, "state_id": 23, "name_en": "Coimbatore", "name_hi": "कोयम्बटूर"},
    {"id": 5, "state_id": 23, "name_en": "Cuddalore", "name_hi": "कड्डालोर"},
    {"id": 6, "state_id": 23, "name_en": "Dharmapuri", "name_hi": "धर्मपुरी"},
    {"id": 7, "state_id": 23, "name_en": "Dindigul", "name_hi": "दिनदिगुल"},
    {"id": 8, "state_id": 23, "name_en": "Erode", "name_hi": "एरोड"},
    {
      "id": 9,
      "state_id": 23,
      "name_en": "Kallakurichi",
      "name_hi": "कल्लाकुरिची",
    },
    {
      "id": 10,
      "state_id": 23,
      "name_en": "Kancheepuram",
      "name_hi": "कांचीपुरम",
    },
    {
      "id": 11,
      "state_id": 23,
      "name_en": "Kanniyakumari",
      "name_hi": "कन्याकुमारी",
    },
    {"id": 12, "state_id": 23, "name_en": "Karur", "name_hi": "करूर"},
    {
      "id": 13,
      "state_id": 23,
      "name_en": "Krishnagiri",
      "name_hi": "कृष्णागिरी",
    },
    {"id": 14, "state_id": 23, "name_en": "Madurai", "name_hi": "मदुरै"},
    {
      "id": 15,
      "state_id": 23,
      "name_en": "Mayiladuthurai",
      "name_hi": "मयिलादुथुरै",
    },
    {
      "id": 16,
      "state_id": 23,
      "name_en": "Nagapattinam",
      "name_hi": "नागपट्टिनम",
    },
    {"id": 17, "state_id": 23, "name_en": "Namakkal", "name_hi": "नामक्कल"},
    {"id": 18, "state_id": 23, "name_en": "Nilgiris", "name_hi": "निलगिरी"},
    {"id": 19, "state_id": 23, "name_en": "Perambalur", "name_hi": "पेरम्बलूर"},
    {
      "id": 20,
      "state_id": 23,
      "name_en": "Pudukkottai",
      "name_hi": "पुडुक्कोट्टई",
    },
    {
      "id": 21,
      "state_id": 23,
      "name_en": "Ramanathapuram",
      "name_hi": "रमनथपुरम",
    },
    {"id": 22, "state_id": 23, "name_en": "Ranipet", "name_hi": "रानीपेट"},
    {"id": 23, "state_id": 23, "name_en": "Salem", "name_hi": "सेलम"},
    {"id": 24, "state_id": 23, "name_en": "Sivaganga", "name_hi": "सिवगंगा"},
    {"id": 25, "state_id": 23, "name_en": "Tenkasi", "name_hi": "तेनकासी"},
    {"id": 26, "state_id": 23, "name_en": "Thanjavur", "name_hi": "थंजावुर"},
    {
      "id": 27,
      "state_id": 23,
      "name_en": "The Nilgiris",
      "name_hi": "द निलगिरीस",
    },
    {"id": 28, "state_id": 23, "name_en": "Theni", "name_hi": "थेनी"},
    {
      "id": 29,
      "state_id": 23,
      "name_en": "Thiruvallur",
      "name_hi": "थिरुवल्लुर",
    },
    {"id": 30, "state_id": 23, "name_en": "Thiruvarur", "name_hi": "थिरुवरूर"},
    {
      "id": 31,
      "state_id": 23,
      "name_en": "Tiruchirappalli",
      "name_hi": "तिरुचिरापल्ली",
    },
    {
      "id": 32,
      "state_id": 23,
      "name_en": "Tirunelveli",
      "name_hi": "तिरुनेलवेली",
    },
    {"id": 33, "state_id": 23, "name_en": "Tiruppur", "name_hi": "तिरुपुर"},
    {
      "id": 34,
      "state_id": 23,
      "name_en": "Tiruvannamalai",
      "name_hi": "तिरुवन्नमलाई",
    },
    {"id": 35, "state_id": 23, "name_en": "Vellore", "name_hi": "वेल्लोर"},
    {
      "id": 36,
      "state_id": 23,
      "name_en": "Viluppuram",
      "name_hi": "विलुप्पुरम",
    },
    {
      "id": 37,
      "state_id": 23,
      "name_en": "Virudhunagar",
      "name_hi": "विरुधुनगर",
    },
  ];

  static final List<Map<String, dynamic>> telanganaDistricts = [
    {"id": 1, "state_id": 24, "name_en": "Adilabad", "name_hi": "अदिलाबाद"},
    {
      "id": 2,
      "state_id": 24,
      "name_en": "Bhadradri Kothagudem",
      "name_hi": "भद्राद्री कोठागुडेम",
    },
    {"id": 3, "state_id": 24, "name_en": "Hyderabad", "name_hi": "हैदराबाद"},
    {"id": 4, "state_id": 24, "name_en": "Jagtial", "name_hi": "जगतियाल"},
    {"id": 5, "state_id": 24, "name_en": "Jangaon", "name_hi": "जंगौन"},
    {
      "id": 6,
      "state_id": 24,
      "name_en": "Jayashankar Bhupalpally",
      "name_hi": "जयशंकर भूपालपल्ली",
    },
    {
      "id": 7,
      "state_id": 24,
      "name_en": "Jogulamba Gadwal",
      "name_hi": "जोगुलम्बा गदवाल",
    },
    {"id": 8, "state_id": 24, "name_en": "Kamareddy", "name_hi": "कमारेड्डी"},
    {"id": 9, "state_id": 24, "name_en": "Karimnagar", "name_hi": "करीमनगर"},
    {"id": 10, "state_id": 24, "name_en": "Khammam", "name_hi": "खम्मम"},
    {
      "id": 11,
      "state_id": 24,
      "name_en": "Komaram Bheem Asifabad",
      "name_hi": "कोमरम भीम असिफाबाद",
    },
    {
      "id": 12,
      "state_id": 24,
      "name_en": "Mahabubabad",
      "name_hi": "महबूबाबाद",
    },
    {
      "id": 13,
      "state_id": 24,
      "name_en": "Mahabubnagar",
      "name_hi": "महबूबनगर",
    },
    {"id": 14, "state_id": 24, "name_en": "Mancherial", "name_hi": "मंचेरियल"},
    {"id": 15, "state_id": 24, "name_en": "Medak", "name_hi": "मेडक"},
    {
      "id": 16,
      "state_id": 24,
      "name_en": "Medchal–Malkajgiri",
      "name_hi": "मेडचल-मलकजगिरी",
    },
    {"id": 17, "state_id": 24, "name_en": "Mulugu", "name_hi": "मुलुगु"},
    {
      "id": 18,
      "state_id": 24,
      "name_en": "Nagarkurnool",
      "name_hi": "नगरकुर्नूल",
    },
    {"id": 19, "state_id": 24, "name_en": "Nalgonda", "name_hi": "नलगोंडा"},
    {"id": 20, "state_id": 24, "name_en": "Narayanpet", "name_hi": "नारायणपेट"},
    {"id": 21, "state_id": 24, "name_en": "Nirmal", "name_hi": "निर्मल"},
    {"id": 22, "state_id": 24, "name_en": "Nizamabad", "name_hi": "निज़ामाबाद"},
    {
      "id": 23,
      "state_id": 24,
      "name_en": "Peddapalli",
      "name_hi": "पेड्डापल्ली",
    },
    {
      "id": 24,
      "state_id": 24,
      "name_en": "Rajanna Sircilla",
      "name_hi": "राजन्ना सिरसिला",
    },
    {
      "id": 25,
      "state_id": 24,
      "name_en": "Rangareddy",
      "name_hi": "रंगारेड्डी",
    },
    {
      "id": 26,
      "state_id": 24,
      "name_en": "Sangareddy",
      "name_hi": "संगारेड्डी",
    },
    {"id": 27, "state_id": 24, "name_en": "Siddipet", "name_hi": "सिद्धिपेट"},
    {"id": 28, "state_id": 24, "name_en": "Suryapet", "name_hi": "सूर्यापेट"},
    {"id": 29, "state_id": 24, "name_en": "Vikarabad", "name_hi": "विकराबाद"},
    {"id": 30, "state_id": 24, "name_en": "Wanaparthy", "name_hi": "वनपार्थी"},
    {
      "id": 31,
      "state_id": 24,
      "name_en": "Warangal Rural",
      "name_hi": "वरंगल ग्रामीण",
    },
    {
      "id": 32,
      "state_id": 24,
      "name_en": "Warangal Urban",
      "name_hi": "वरंगल शहरी",
    },
    {
      "id": 33,
      "state_id": 24,
      "name_en": "Yadadri Bhuvanagiri",
      "name_hi": "यादाद्री भुवनगिरी",
    },
  ];

  static final List<Map<String, dynamic>> tripuraDistricts = [
    {"id": 1, "state_id": 25, "name_en": "Dhalai", "name_hi": "धलाई"},
    {"id": 2, "state_id": 25, "name_en": "Gomati", "name_hi": "गोमती"},
    {"id": 3, "state_id": 25, "name_en": "Khowai", "name_hi": "खोवाई"},
    {
      "id": 4,
      "state_id": 25,
      "name_en": "North Tripura",
      "name_hi": "उत्तरी त्रिपुरा",
    },
    {"id": 5, "state_id": 25, "name_en": "Sepahijala", "name_hi": "सेपाहीजाला"},
    {
      "id": 6,
      "state_id": 25,
      "name_en": "South Tripura",
      "name_hi": "दक्षिण त्रिपुरा",
    },
    {"id": 7, "state_id": 25, "name_en": "Unakoti", "name_hi": "उनाकोटी"},
    {
      "id": 8,
      "state_id": 25,
      "name_en": "West Tripura",
      "name_hi": "पश्चिम त्रिपुरा",
    },
  ];

  static final List<Map<String, dynamic>> uttarPradeshDistricts = [
    {"id": 1, "state_id": 26, "name_en": "Agra", "name_hi": "आगरा"},
    {"id": 2, "state_id": 26, "name_en": "Aligarh", "name_hi": "अलीगढ़"},
    {"id": 3, "state_id": 26, "name_en": "Prayagraj", "name_hi": "प्रयागराज"},
    {
      "id": 4,
      "state_id": 26,
      "name_en": "Ambedkar Nagar",
      "name_hi": "अंबेडकर नगर",
    },
    {"id": 5, "state_id": 26, "name_en": "Amethi", "name_hi": "अमेठी"},
    {"id": 6, "state_id": 26, "name_en": "Amroha", "name_hi": "अमरौहा"},
    {"id": 7, "state_id": 26, "name_en": "Auraiya", "name_hi": "औरेया"},
    {"id": 8, "state_id": 26, "name_en": "Ayodhya", "name_hi": "अयोध्या"},
    {"id": 9, "state_id": 26, "name_en": "Azamgarh", "name_hi": "आजमगढ़"},
    {"id": 10, "state_id": 26, "name_en": "Baghpat", "name_hi": "बागपत"},
    {"id": 11, "state_id": 26, "name_en": "Bahraich", "name_hi": "बहराइच"},
    {"id": 12, "state_id": 26, "name_en": "Ballia", "name_hi": "बलिया"},
    {"id": 13, "state_id": 26, "name_en": "Balrampur", "name_hi": "बलरामपुर"},
    {"id": 14, "state_id": 26, "name_en": "Banda", "name_hi": "बांदा"},
    {"id": 15, "state_id": 26, "name_en": "Barabanki", "name_hi": "बाराबंकी"},
    {"id": 16, "state_id": 26, "name_en": "Bareilly", "name_hi": "बरेली"},
    {"id": 17, "state_id": 26, "name_en": "Basti", "name_hi": "बस्ती"},
    {"id": 18, "state_id": 26, "name_en": "Bhadohi", "name_hi": "भदोही"},
    {"id": 19, "state_id": 26, "name_en": "Bijnor", "name_hi": "बिजनोर"},
    {"id": 20, "state_id": 26, "name_en": "Budaun", "name_hi": "बदायूं"},
    {"id": 21, "state_id": 26, "name_en": "Bulandshahr", "name_hi": "बुलंदशहर"},
    {"id": 22, "state_id": 26, "name_en": "Chandauli", "name_hi": "चंदौली"},
    {"id": 23, "state_id": 26, "name_en": "Chitrakoot", "name_hi": "चित्रकूट"},
    {"id": 24, "state_id": 26, "name_en": "Deoria", "name_hi": "देवरिया"},
    {"id": 25, "state_id": 26, "name_en": "Etah", "name_hi": "एटा"},
    {"id": 26, "state_id": 26, "name_en": "Etawah", "name_hi": "एटावा"},
    {
      "id": 27,
      "state_id": 26,
      "name_en": "Ayodhya (Faizabad)",
      "name_hi": "अयोध्या (फ़ैज़ाबाद)",
    },
    {
      "id": 28,
      "state_id": 26,
      "name_en": "Farrukhabad",
      "name_hi": "फ़र्रुख़ाबाद",
    },
    {"id": 29, "state_id": 26, "name_en": "Fatehpur", "name_hi": "फतेहपुर"},
    {
      "id": 30,
      "state_id": 26,
      "name_en": "Firozabad",
      "name_hi": "फ़िरोज़ाबाद",
    },
    {
      "id": 31,
      "state_id": 26,
      "name_en": "Gautam Buddha Nagar",
      "name_hi": "गौतम बुद्ध नगर",
    },
    {
      "id": 32,
      "state_id": 26,
      "name_en": "Ghaziabad",
      "name_hi": "ग़ाज़ियाबाद",
    },
    {"id": 33, "state_id": 26, "name_en": "Ghazipur", "name_hi": "गाज़ीपुर"},
    {"id": 34, "state_id": 26, "name_en": "Gonda", "name_hi": "गोंडा"},
    {"id": 35, "state_id": 26, "name_en": "Gorakhpur", "name_hi": "गोरखपुर"},
    {"id": 36, "state_id": 26, "name_en": "Hamirpur", "name_hi": "हमीरपुर"},
    {"id": 37, "state_id": 26, "name_en": "Hapur", "name_hi": "हापुर"},
    {"id": 38, "state_id": 26, "name_en": "Hardoi", "name_hi": "हारदोई"},
    {"id": 39, "state_id": 26, "name_en": "Hathras", "name_hi": "हथरस"},
    {"id": 40, "state_id": 26, "name_en": "Jalaun", "name_hi": "जालौन"},
    {"id": 41, "state_id": 26, "name_en": "Jaunpur", "name_hi": "जौनपुर"},
    {"id": 42, "state_id": 26, "name_en": "Jhansi", "name_hi": "झांसी"},
    {"id": 43, "state_id": 26, "name_en": "Kannauj", "name_hi": "कन्नौज"},
    {
      "id": 44,
      "state_id": 26,
      "name_en": "Kanpur Dehat",
      "name_hi": "कानपुर देहात",
    },
    {
      "id": 45,
      "state_id": 26,
      "name_en": "Kanpur Nagar",
      "name_hi": "कानपुर नगर",
    },
    {"id": 46, "state_id": 26, "name_en": "Kasganj", "name_hi": "कासगंज"},
    {"id": 47, "state_id": 26, "name_en": "Kaushambi", "name_hi": "कौशांबी"},
    {
      "id": 48,
      "state_id": 26,
      "name_en": "Kheri (Lakhimpur Kheri)",
      "name_hi": "खीरी (लखीमपुर खीरी)",
    },
    {"id": 49, "state_id": 26, "name_en": "Kushinagar", "name_hi": "कुशीनगर"},
    {"id": 50, "state_id": 26, "name_en": "Lucknow", "name_hi": "लखनऊ"},
    {"id": 51, "state_id": 26, "name_en": "Maharajganj", "name_hi": "महराजगंज"},
    {"id": 52, "state_id": 26, "name_en": "Mahoba", "name_hi": "महोबा"},
    {"id": 53, "state_id": 26, "name_en": "Mainpuri", "name_hi": "मैनपुरी"},
    {"id": 54, "state_id": 26, "name_en": "Mathura", "name_hi": "मथुरा"},
    {"id": 55, "state_id": 26, "name_en": "Mau", "name_hi": "मऊ"},
    {"id": 56, "state_id": 26, "name_en": "Meerut", "name_hi": "मेरठ"},
    {"id": 57, "state_id": 26, "name_en": "Mirzapur", "name_hi": "मिर्ज़ापुर"},
    {"id": 58, "state_id": 26, "name_en": "Moradabad", "name_hi": "मुरादाबाद"},
    {
      "id": 59,
      "state_id": 26,
      "name_en": "Muzaffarnagar",
      "name_hi": "मुज़फ़्फ़रनगर",
    },
    {"id": 60, "state_id": 26, "name_en": "Pilibhit", "name_hi": "पिलिभीत"},
    {"id": 61, "state_id": 26, "name_en": "Pratapgarh", "name_hi": "प्रतापगढ़"},
    {"id": 62, "state_id": 26, "name_en": "Raebareli", "name_hi": "रायबरेली"},
    {"id": 63, "state_id": 26, "name_en": "Rampur", "name_hi": "रामपुर"},
    {"id": 64, "state_id": 26, "name_en": "Saharanpur", "name_hi": "सहारनपुर"},
    {"id": 65, "state_id": 26, "name_en": "Sambhal", "name_hi": "संभल"},
    {
      "id": 66,
      "state_id": 26,
      "name_en": "Shahjahanpur",
      "name_hi": "शाहजहांपुर",
    },
    {"id": 67, "state_id": 26, "name_en": "Shamli", "name_hi": "शामली"},
    {
      "id": 68,
      "state_id": 26,
      "name_en": "Shahjahanpur",
      "name_hi": "शाहजहाँपुर",
    },
    {"id": 69, "state_id": 26, "name_en": "Sitapur", "name_hi": "सीतापुर"},
    {"id": 70, "state_id": 26, "name_en": "Sonbhadra", "name_hi": "सोनभद्र"},
    {"id": 71, "state_id": 26, "name_en": "Sultanpur", "name_hi": "सुलतानपुर"},
    {"id": 72, "state_id": 26, "name_en": "Unnao", "name_hi": "उन्नाव"},
    {"id": 73, "state_id": 26, "name_en": "Varanasi", "name_hi": "वाराणसी"},
  ];

  static final List<Map<String, dynamic>> uttarakhandDistricts = [
    {"id": 1, "state_id": 27, "name_en": "Almora", "name_hi": "अल्मोड़ा"},
    {"id": 2, "state_id": 27, "name_en": "Bageshwar", "name_hi": "बागेश्वर"},
    {"id": 3, "state_id": 27, "name_en": "Chamoli", "name_hi": "चमोली"},
    {"id": 4, "state_id": 27, "name_en": "Champawat", "name_hi": "चंपावत"},
    {"id": 5, "state_id": 27, "name_en": "Dehradun", "name_hi": "देहरादून"},
    {"id": 6, "state_id": 27, "name_en": "Haridwar", "name_hi": "हरिद्वार"},
    {"id": 7, "state_id": 27, "name_en": "Nainital", "name_hi": "नैनीताल"},
    {
      "id": 8,
      "state_id": 27,
      "name_en": "Pauri Garhwal",
      "name_hi": "पौड़ी गढ़वाल",
    },
    {"id": 9, "state_id": 27, "name_en": "Pithoragarh", "name_hi": "पिथोरागढ़"},
    {
      "id": 10,
      "state_id": 27,
      "name_en": "Rudraprayag",
      "name_hi": "रुद्रप्रयाग",
    },
    {
      "id": 11,
      "state_id": 27,
      "name_en": "Tehri Garhwal",
      "name_hi": "टेहरी गढ़वाल",
    },
    {
      "id": 12,
      "state_id": 27,
      "name_en": "Udham Singh Nagar",
      "name_hi": "उधम सिंह नगर",
    },
    {"id": 13, "state_id": 27, "name_en": "Uttarkashi", "name_hi": "उत्तरकाशी"},
  ];

  static final List<Map<String, dynamic>> westBengalDistricts = [
    {
      "id": 1,
      "state_id": 28,
      "name_en": "Alipurduar",
      "name_hi": "आलिपुरद्वार",
    },
    {"id": 2, "state_id": 28, "name_en": "Bankura", "name_hi": "बांकुरा"},
    {"id": 3, "state_id": 28, "name_en": "Birbhum", "name_hi": "बीरभूम"},
    {"id": 4, "state_id": 28, "name_en": "Cooch Behar", "name_hi": "कूचबिहार"},
    {
      "id": 5,
      "state_id": 28,
      "name_en": "Dakshin Dinajpur",
      "name_hi": "दक्षिण दिनाजपुर",
    },
    {"id": 6, "state_id": 28, "name_en": "Darjeeling", "name_hi": "दार्जिलिंग"},
    {"id": 7, "state_id": 28, "name_en": "Hooghly", "name_hi": "हुगली"},
    {"id": 8, "state_id": 28, "name_en": "Howrah", "name_hi": "हावड़ा"},
    {"id": 9, "state_id": 28, "name_en": "Jalpaiguri", "name_hi": "जलपाईगुड़ी"},
    {"id": 10, "state_id": 28, "name_en": "Jhargram", "name_hi": "झारग्राम"},
    {"id": 11, "state_id": 28, "name_en": "Kalimpong", "name_hi": "कालिम्पोंग"},
    {"id": 12, "state_id": 28, "name_en": "Kolkata", "name_hi": "कोलकाता"},
    {"id": 13, "state_id": 28, "name_en": "Malda", "name_hi": "मालदा"},
    {
      "id": 14,
      "state_id": 28,
      "name_en": "Murshidabad",
      "name_hi": "मुर्शिदाबाद",
    },
    {"id": 15, "state_id": 28, "name_en": "Nadia", "name_hi": "नादिया"},
    {
      "id": 16,
      "state_id": 28,
      "name_en": "North 24 Parganas",
      "name_hi": "उत्तर 24 परगना",
    },
    {
      "id": 17,
      "state_id": 28,
      "name_en": "Paschim Bardhaman",
      "name_hi": "पश्चिम बर्द्धमान",
    },
    {
      "id": 18,
      "state_id": 28,
      "name_en": "Paschim Medinipur",
      "name_hi": "पश्चिम मिदनापुर",
    },
    {
      "id": 19,
      "state_id": 28,
      "name_en": "Purba Bardhaman",
      "name_hi": "पूर्व बर्द्धमान",
    },
    {
      "id": 20,
      "state_id": 28,
      "name_en": "Purba Medinipur",
      "name_hi": "पूर्व मिदनापुर",
    },
    {"id": 21, "state_id": 28, "name_en": "Purulia", "name_hi": "पुरुलिया"},
    {
      "id": 22,
      "state_id": 28,
      "name_en": "South 24 Parganas",
      "name_hi": "दक्षिण 24 परगना",
    },
    {
      "id": 23,
      "state_id": 28,
      "name_en": "Uttar Dinajpur",
      "name_hi": "उत्तर दिनाजपुर",
    },
  ];
}
