const Map<String, String> enUS = {
  'login': 'Login',
  'app_version': 'App Version @version',
  'enter_mobile_number': "Enter Mobile Number",
  "enter_password": "Enter Password",
  "not_registered_yet": "Not registered yet?",
  "register_now": "Register Now",
  "choose_lang": "Choose Language",
  "choose_lang_msg": "Select your desired langauge to use!",
  "personal_detail": "Personal Details",
  "please_select_time_also": "Please select time  also",
  "future_date/time_not_allowed": "Future date/time not allowed",
  "enter_fullname": "Enter Full Name",
  "enter_otp": "Enter 6 digit OTP",
  "next": "Next",
  "dairy_center_detail": "Dairy Center Detail",
  "loading": "Loading...",
  "details_missing": "Details Missing!",
  "add_details": "Add Details",
  "dairy_details_missing_msg":
      "The dairy Info is missing, Please add Dairy Details to continue using feature of App.",
  "delete_account_warning":
      "Your All Data and account will be remove forever, Do you want to continue?",
  "request_sent": "Request Sent",
  "delete_account": "Delete Account",
  "account_delete_msg": "Your Account  will be delete in 1-2 days. ",
  "account_withdraw_msg":
      "Do you want to withdraw your account delete request?",
  "withdraw": "Withdraw",
  "app_logout_msg": "You will logged out from app, Do you want to continue?",
  "logout": "Logout",
  "maybe_later": "Maybe Later!",
  "free_trail_expired": "Free Trial Expired!",
  "free_trial_expired_msg_part1":
      "Your 7-days free trial has come to an \nend. To continue using all the \npremium features of ",
  "free_trial_expired_msg_part2": "Dairy Vikas",
  "free_trial_expired_msg_part3": "\nplease upgrade your plan.",
  "enter_dairyname": "Enter Dairy Name",
  "enter_village_name": "Enter Village Name",
  "enter_taluka_name": "Enter Taluka Name",
  "enter_pincode_number": "Enter Pincode Number",
  "select_state": "Select State",
  "enter_district": "Enter District Name",
  "select_district": "Select District",
  "dairy_center_settings": "Dairy Center Settings",
  "select_collection_type": "Select Collection Type",
  "select_milk_type": "Select Milk Type",
  "select_collection_shift": "Select Collection Shift",
  "select_payment_period": "Select Payment Period",
  "upgrade_now": "Upgrade Now",
  "free_trial_msg": "Free trial Ends in @days Days",
  "operations": "Operations",
  "farmer_finance": "Farmer & Finance",
  "insights_communication": "Insights & Communication",
  "verify": "Verify",
  "verify_otp": "Verify OTP",
  "edit": "Edit",
  "resend_otp": "Resend Otp in",
  "skip": "Skip",
  "dariy_details_added": "Dairy details saved!",
  "dairy_details_missing": "Dairy details missing",
  "select_option": "Select Option",
  "add_photo": "Add Photo",
  "change_photo": "Change Photo",
  "add_text_thought": "Add Text Thought",
  "remove_thought": "Remove Thought",
  "view_thought": "View Thought",
  "add_photo_thought": "Add Photo Thought",
  "terms_and_conditions": "Terms & Conditions",
  "i_have_agree": "I have read and agreed to the ",
  "choose_photo": "Choose Photo",
  "camera": "Camera",
  "gallary": "Gallary",
  "verified": "Verified",
  "forgot_password": "Forgot Password",
  "enter_registred_mobile_number": "Enter Registred Mobile Number",
  "enter_otp_number": "Enter Otp Number",
  "enter_new_password": "Enter New Password",
  "get_otp": "Get OTP",
  "unavailable": "Unavailable",
  'unknown': "Unknown",
  'search_customer': "Search Customer by name or code",
  "reset_password": "Reset Password",
  "press_again_to_exit": "Press again to exit.",
  "something_went_wrong_from_server": "Something went wrong from server.",
  "try_again": "Try Again",
  "app_update_available": "App Update Available!",
  "app_update_message":
      "A new version of the app is available. Please update to continue using Dairy Vikas.",
  "update_now": "Update Now",

  // error messages
  "we_have_sent_otp": "We have sent OTP to you number",
  "accept_terms": "Please Accept terms and conditions",
  "name_required": "Name is required",
  "otp_required": "Enter 6 digit OTP",
  "chart_name_required": "Chart name is required",
  "invalid_chart_name": "Chart name is  Invalid",
  "invalid_name": "Name is  Invalid",

  "phone_required": "Phone Number is Required",
  "invalid_phone": "Phone Number is Invalid",
  "password_required": "Password is Required",
  "password_length": "Password must be at least 6 characters",
  "dairyname_required": "Dairy name is required",
  "village_name_required": "Village name is required",
  "taluka_name_required": "Taluka name is required",
  "pincode_required": "Pincode is required",
  "invalid_pincode": "Invalid Pincode",
  "district_required": "District is required",
  "state_required": "State is required",

  // rate charts keys
  "fat": "Fat",
  "fat_from": "Fat \nFrom",
  "fat_to": "Fat \nTo",
  "snf_from": "Snf \nFrom",
  "snf_to": "Snf \nTo",
  'clr_from': "Clr \nFrom",
  'clr_to': "Clr \nTo",
  'clr_from2': "Clr From",
  'clr_to2': "Clr To",
  "fat_from2": "Fat From",
  "fat_to2": "Fat To",
  "snf_from2": "Snf From",
  "snf_to2": "Snf To",
  "snf": "SNF",
  "fat_snf": "Fat/SNF",
  "clr": "Clr",
  "fat_clr": "Fat/CLR",
  "add_fat_step": "Add Fat Step",
  "add_snf_step": "Add SNF Step",
  "add_clr_step": "Add Clr Step",

  "bonus_penalty": "Bonus/Penalty",
  "bonus_penalty_on_fat": "Bonus/Penalty on Fat",
  "bonus_penalty_on_snf": "Bonus/Penalty on SNF",
  "bonus_penalty_on_clr": "Bonus/Penalty on Clr",
  "from": "From",
  "to": "To",
  "rate": "Rate",
  "add": "Add",
  "add_dynamic": "Add @type",
  "add_bonus": "Add Bonus",
  "add_penalty": "Add Penalty",
  "bonus": "Bonus",
  "penalty": "Penalty",
  "rate_chart": "Rate Chart",
  "fat_only": "FAT",
  "base_amount": "Base Amount",
  "add_step": "Add Step",
  "add_bonus_penalty": "Add Bonus / Penalty",
  "add_total_solid_step": "Add Total Solid Step",
  "select_chart_type_format":
      "Select chart type and format\nto create your new chart.",
  "no_chart_available": "No Chart Available",
  "step": "Step",
  "amount": "Amount",
  "add_rate_chart": "Add Rate chart",
  "save": "Save",
  "select_formate": "Select Formate",
  "select_chart_type": "Select Chart Type",
  "enter_chart_name": "Enter Chart Name",
  "enter_fixed_rate": "Enter fixed Rate",
  "add_fixed_rate": "Add fixed Rate",
  "fixed_rate": "Fixed Rate",
  "change": "Change",
  "update": "Update",
  "adjustment": "Adjustment: ",
  "edit_rate_chart": "Edit Rate Chart",
  "rate_charts": "Rate Charts",
  "no_rate_charts_found": "No Rate chart found!",
  "add_now": "Add now",
  "assign_to": "Assign To ",
  "select_chart_shift": "Select chart shift",
  "assign_already": "Already assigned",
  "assign": "Assign",
  "type": "Type",
  "sno": "s.No.",
  "select_to_assign": "Select to assign",
  "assign_rate_chart": "Assign Rate chart",
  "assigned_dynamic": "Assigned (@count)",
  "selected_dynamic": "Selected (@count)",
  "selecte_all": "Select all",
  "show_selected": "Show Selected",
  "unassign": "Unassign",
  "search_supplier": "Search supplier by name or code",
  "milk_type": "Milk Type: ",
  "cow_milk": "Cow Milk",
  "buffalo_milk": "Buffalo Milk",
  "category": "Category: ",
  "collection": "Collection",
  "milk_sale": "Milk Sale",
  "applied_to": "Applied To: ",
  "dairy_dynamic": "Dairy(@count)",
  "supplier_dynamic": "Supplier(@count)",
  "delete": "Delete",
  "inactive": "Inactive",
  "all": "All",
  "active": "Active",
  'assigned': "Assigned",
  "morning": "Morning",
  "evening": "Evening",
  "morning_evening": "Morning+Evening",
  "yes": "Yes",
  "cancel": "Cancel",
  "cow_buffalo": "Cow + Buffalo",
  "cow": "Cow",
  "buffalo": "Buffalo",
  "choose_excel": "Choose Excel: ",
  "select_excel": "Select Your Excel File",
  "choose": "Choose",
  "upload": "upload",
  "adjust_rate_chart_amount": "Adjust Rate Chart Amount",
  "please_enter_adjustment_amount": "Please enter adjustment amount",
  "no_unassigned_supplier": "No UnAssigned supplier available",
  "delete_rate_chart_warning":
      "All assignments will be removed after deleting this chart. Do you want to delete?",
  "activate_rate_chart_warning":
      "This rate chart is inactive. Do you want to activate this chart?",
  "inactivate_rate_chart_warning":
      "This rate chart is active. Do you want to inactivate it? After inactivation, all assignments will be removed.",

  // milk suppliers strings....
  "update_supplier": "Update Supplier",
  "add_supplier": "Add Supplier",
  "enter_supplier_code": "Enter Supplier Code",
  "enter_supplier_name": "Enter Supplier Name",
  "select_status": "Select Status",
  "supplier_details": "Supplier Details",
  "supplier_code": "Supplier Code",
  'remove_supplier_warning_message':
      "Are you sure that you want to remove @name?",
  "full_name": "Full Name",
  "supplier_mobile": "Supplier Mobile",
  "supplier_email": "Supplier Email",
  "status": "Status",
  "added_on": "Added on",
  "remove_supplier": "Remove Supplier",
  "no_inactive_supplier_found": "No Inactive Supplier Found",
  "no_supplier_found": "No Supplier Found",
  "active:": "Active: ",
  "inactive:": "InActive: ",
  "total:": "Total: ",
  "warning": "Warning!",
  "supplier_active_inactive_message":
      'This Supplier is  Active, do you want to Inactive?',
  "supplier_inactive_active_message":
      'This Supplier is  Inactive, do you want to Active?',
  "suppliers": "Suppliers",
  "actions": "Actions",
  "all_supplier": "All Suppliers",
  "no_assigned_supplier": "No Assigned supplier found",
  "code:": "Code: @code",
  "unassign_to": "UnAssign To",
  "total": "Total",

  // rate chart error messages
  "rate.fat_required": "Fat values and rate are required",
  "rate.snf_required": "Snf values and rate are required",
  "rate.clr_required": "Clr values and rate are required",

  "rate.fat_range": "Fat range is from 2.0 to 15.0",
  "rate.snf_range": "Snf range is from 4.0 to 15.0",
  "rate.clr_range": "Clr range is from 20.0 to 32.0",

  "rate.fat_step_required": "Fat step and amount are required",
  "rate.snf_step_required": "Snf step and amount are required",
  "rate.clr_step_required": "Clr step and amount are required",

  "rate.fat_step_range": "Fat step range is from 2.0 to 15.0",
  "rate.snf_step_range": "Snf step range is from 4.0 to 15.0",
  "rate.clr_step_range": "Clr step range is from 20.0 to 32.0",

  "rate.step_greater_than": "@type step should be greater than @value",

  "rate.fat_snf_required": "Fat, Snf values and rate are required",
  "empty_rate_chart": "Your Rate chart is empty",
  "upload_excel_file": "Please upload only excel file",
  "select_at_least_shift": "Please select at least one shift",

  // collection strings....
  "update_collection": "Update Collection",
  "add_collection": "Add Collection",
  "remove_collection_message":
      "All Data will be lost, do you want to delete this collection?",
  "select_date": "Select Date",
  "select_suppliers": "Select Suppliers",
  "search": "Search",
  "sample": "Sample",
  "is_inactive": "@name is Inactive",
  "enter_liter": "Enter Liter",
  "enter_fat": "Enter Fat",
  "enter_snf": "Enter SNF",
  "add_can": "Add Can",
  "can_count": "Can: @count",
  "total_cans_added": "Total Can(s) Added",
  "total_liter": "Total Liters",
  "total_amount": "Total Amount",
  "previous": "Previous",
  "w_scale": "W-Scale",
  "can": "Can",
  "code_count": "Count: @count",
  "adjust_collection": "Adjust Collection",
  "search_suppliers_by_code_message":
      "Enter Code and press below button to search suppliers collection from @start to @end",
  "select_date_range": "Select Date Range",
  "no_date_range_available": "No Date Range Available!",
  'code': "Code",
  'search_collection': "Search Collection",
  "collections": "Collections",
  "show_full_data": "Show Full data",
  "hide_full_data": "Hide Full data",
  'liter': "Liter",
  "no_collection_found": "No Collection Found!",
  'sort_by': "Sort By",
  'absent:': "Absent: ",
  "present:": "Present: ",
  "collection_adjustment": "Collection Adjustment",
  'print': 'Print',
  'download_excel': "Download Excel",
  "sms_status": "SMS Status",
  "update_collection_rate": "Update Collection Rate",
  "collection_sheet": "Collection Sheet",
  "names/details": "Names/Details",
  "shift/type": "Shift/Type",
  'fat: ': "FAT: ",
  'snf: ': "SNF: ",
  'sort_by_time': "Sort By Time",
  'sort_by_amount_ascending': "Sort By Amount(Ascending)",
  'sort_by_amount_descending': "Sort By Amount(Descending)",

  // collection validation messages
  "select_a_date_to_add_collection": "Please select a date to add collection",
  "select_a_supplier_first": "Please select a supplier first",
  "please_select_a_active_supplier": "Please select a active supplier",
  'please_add_collection_liter': "Please add collection liter",
  "please_add_fat_point": "Please add fat point",
  "please_add_snf_or_clr_point": "Please add snf or clr point",
  "rate_is_empty": "Rate is empty",

  // milk sale strings....
  "add_sale": "Add Milk Sale",
  "update_sale": "Update Milk Sale",
  "milk_buyers": "Milk Buyers",
  "bill": "Bill",
  "no_milksale_found": "No Milk Sale Found!",
  "update_buyer": "Update Buyer",
  "add_buyer": "Add Buyer",
  "enter_buyer_code": "Enter Buyer Code",
  "enter_buyer_name": "Enter Buyer Name",
  "select_rate_type": "Select Rate Type",
  "fixed_milk_sale_rate": "Fixed Milk Sale Rate",
  "all_buyers": "All Buyers",
  "fixed_cow_rate": "Fixed Cow Rate",
  "fixed_buffalo_rate": "Fixed Buffalo Rate",
  "no_buyer_found": "No Buyer Found",
  "search_buyer": "Search Buyer",
  "remove": "Remove",
  "buyers_active_inactive_message":
      'This Buyer is  Active, do you want to Inactive?',
  "buyers_inactive_active_message":
      'This Buyer is  Inactive, do you want to Active?',
  "buyers": "Buyers",
  'date_can_not_be_change': "Date can not be change",
  'select_a_date_to_add_sale': "Select a Date to add Sale",
  "select_a_buyer_first": "Select a buyer first",
  "select_a_active_buyer": "Please select a active buyer",
  "please_add_sale_liter": "Please add sale liter",

  // food section strings....
  "food_dealers": "Food Dealers",
  "no_dealer_found": 'No Dealer Found!',
  "search_dealer": "Search Dealer by name or code",
  "add_dealer": "Add Dealer",
  "update_dealer": "Update Dealer",
  "enter_dealer_code": "Enter dealer code",
  "enter_dealer_name": "Enter Dealer Name",
  "enter_dealer_address": "Enter dealer address",
  "enter_dealer_remark": "Enter Remark",
  "all_items": "All Items",
  "add_food_sale": "Add Food Sale",
  "update_food_sale": "Update Food Sale",
  "search_supplier_or_buyer": "Search Supplier Or Buyer",
  "enter_food_rate": "Enter Food Rate",

  "no_item_available": "No Item Available",
  "search_item": "Search Item",
  "added_by": "Added by",
  'added_by_you': "Added By You",
  "edit_your_item": "Edit Your Item",
  "add_your_item": "Add Your Item",
  "add_item": "Add Item",
  "enter_your_item_name": "Enter Your Item Name",
  "add_stock": "Add Stock",
  "update_stock": "Update Stock",
  "select_items_to_add": "Select Item to Add",
  "enter_food_qty": "Enter Food Quantity",
  "enter_buy_rate": "Enter Buy Rate",
  "enter_sale_rate": "Enter Sale Rate",
  "unit": "Unit",
  "search_unit": "Search Unit",
  "select_food": "Select Food",
  "dealer_code": "Enter Dealer Code",
  "select_dealer": "Select Dealer",
  "food_stock": "Food Stock",
  "added": "Added: @date",
  "in_stock": "IN STOCK",
  "out_of_stock": "OUT OF STOCK",
  "total_qty": "TOTAL QTY",
  "units": 'Unit(s)',
  "sold/stock": "SOLD/STOCK",
  "sale_rate": 'Sale Rate',
  "history": "History",
  "food_stock_empty": "Food Stock Empty",
  "stock_history": "Stock History",
  "per": "PER @count",
  "buy_price": "BUY PRICE",
  "in_stock_lower": "In Stock",
  "out_of_stock_lower": "Out Of Stock",
  "no_history_found": "No History Found!",
  "food_sales": "Food Sales",
  "update_date": "Updated: @date",
  "created_date": "Created: @date",

  // food validation messages
  "select_dealer_first": "Select a dealer First",
  "please_select_food": "Select a food first",
  "enter_food__buy_rate": "Enter Food Buy Rate",
  "enter_food__sale_rate": "Enter Food Sale Rate",
  "today": "Today",
  "this_week": "This Week",
  "this_month": "This Month",
  "last_month": "Last Month",
  "custom": "Custom",

  // notice board strings...
  "notice_posts": "Notice Posts",
  "posted_on": "Posted On: @date",
  "no_post_yet": "No Post Added!",
  "add_post": "Add Post",
  "update_post": "Update Post",
  "update_your_notice": "Update Your Notice",
  "create_new_notice": "Create New Notice",
  "write_message_to_user":
      "Write a message to your customers(e.g., New item stock is available today.)...",
  "limited_reached": "(Limit reached!)",
  "post_now": "Post Now",
  "customers_will_see_message":
      "Only Your Customers will be able to \nSee your post.",
  "post_remove_message":
      "This Post will be delete forever and can not be restore, do you want to still remove it?",
  "remove_post": "Remove Post",
  "please_write_some_message": " Please write some message",

  // invoice strings...
  "customer_invoices": "Customer Invoices",
  "food_or_item_amount": "Food or Item Amount: ",
  "user": "User: ",
  "status_dynamic": "Status: ",
  "paid": "Paid",
  "pending": "Pending",
  "amount_dynamic": "Amount: @amount",
  "mark_paid": "Mark Paid",
  "no_invoice_found": "No Invoice Found!",
  "search_invoice_by_name_or_code": "Search Invoice by Name or Amount",
  "genrate_invoice": "Genrate Invoice",
  "invoice_details": "Invoice details",
  "dealer_up": "DEALER",
  "supplier_up": "SUPPLIER",

  'mark_receive': "Mark Receive",
  "buyer_up": "BUYER",
  "total_collection_amount": "Total Collection Amount",
  "total_deduction": "Total Deduction",
  "amount_due": "Amount Due",
  "food_or_item": "FOOD OR ITEM",
  "edit_up": "EDIT",
  "product_name_up": "Product Name",
  "deduction_details": "DEDUCTION DETAILS",
  "deduction_type": "DEDUCTION TYPE",
  "total_up": "TOTAL",
  "collections_up": "COLLECTIONS",
  "invoice_genrate": "Invoice Genrated",
  "delete_invoice": "Do you really want to delete this invoice?",
  'total_of_date': "Total of @date",

  // khata string
  "add_customer": "Add Customer",
  "call": "Call",
  "payee": "@count Payee",
  "receivalbes": "@count Receivalbes",
  "you_will_give": "You Will Give",
  "you_will_get": "You Will Get",
  "balance": "Balance: @amount",
  "all_entries": "All Entries",
  "current_balance": "CURRENT BALANCE",
  "got": "GOT",
  "gave": "GAVE",
  "gotr": "Got ₹",
  "gaver": "GAVE ₹",
  "you_are_paying": "You Are Paying",
  "you_are_receving": "You Are Receving",
  "enter_amount": "Enter Amount",
  "enter_a_note": "Enter a Note",
  "no_record_found": "No Khata Record Found!",
  "no_khata_customer_available": "No Khata Customer Avaialable",
  "delete_entry_msg": "This Entry will Permanently, Are You sure to Proceed?",
  "note_unavailable": "Note Unavailable",
  "no_entries_found": "No Entry Found!",
  "add_khata_customer": "Add Khata Customer",
  "update_khata_customer": "Update Khata Customer",
  "enter_customer_name": "Enter Customer Name",
  "select_from_contacts": 'Select From Contacts',
  "delete_customer_msg": "Are you sure you want to delete @name",
  "dairy_sathi_khata": "Dairy Vikas Khata",
  "transaction_record_msg":
      "Transactions Will be recorded automaically \nfor this customer.",
  "please_enter_amount": "Please Enter Amount",
  "enter_valid_amount": "Enter valid amount",

  // Subscripiton plan strings
  "subscriptions": "Subscriptions Plans",
  "choose_plan": "Choose Your Plan",
  "choose_plan_msg":
      "Choose Your favorite plan and grow your bussiness with Dairy Vikas",
  "no_plans_found": "No Plans Found!",
  "best_value": "Best Value",
  "payment_failed": "Payment Failed!",
  "payment_success": "Payment Success!",
  "plan_upgrade_message":
      "Your Subscription Plan Has been Updated Successfully!",
  "transaction_details": "Transaction Details",
  "txnt_id": "Transaction ID",
  "d&t": "Date & Time",
  "payment_method": "Payment Method",
  "plan": "Plan",
  "payment_status": "Payment Status",
  "download_receipt": "Download Receipt",
  "go_to_dashboard": "Go to Dashboard",
  "txs_fail_msg":
      "Your transaction could not be processed. This might be due to insufficient balance or a temporary bank server issue.",
  "amt": "AMOUNT",
  "txnt_id_UP": "TRANSACTION ID",
  "date_up": "DATE",
  "need_help": "Need immediate help?",
  "support_msg":
      "Our support team is available 24/7 to\n assist payment queries",
  "retry_payment": "Retry Payment",
  "success": "success",

  // refer and earn strings
  "refer_and_earn": "Refer & Earn",

  "friends_bring_rewards": "Friends Bring Rewards!",

  "refer_description":
      "Refer your friends and they will get @credits credits and you will get @credits2 credits on their first payment.",

  "credits": "@credits Credits",

  "your_referral_code": "Your Referral Code",

  "copy": "Copy",

  "how_it_works": "How it Works",

  "invite_friends": "Invite Friends",

  "invite_friends_desc": "Share Your Referral Code or Link to your friends",

  "they_register": "They Register",

  "they_register_desc":
      "Your Friend Register and buy their first plan using your referral code or link",

  "you_get_credits": "You Get @credits Credits",

  "you_get_credits_desc":
      "You will receive @credits credits for each friend who joins and makes their first payment using your referral code or link",

  "whatsapp_share": "WhatsApp Share",

  "share_link": "Share Link",
};
