const Map<String, String> hiIN = {
  "login": "लॉगिन",
  "app_version": "ऐप संस्करण @version",
  "enter_mobile_number": "मोबाइल नंबर दर्ज करें",
  "enter_password": "पासवर्ड दर्ज करें",
  "not_registered_yet": "अभी तक रजिस्टर नहीं किया?",
  "register_now": "अभी रजिस्टर करें",
  "choose_lang": "भाषा चुनें",
  "choose_lang_msg": "उपयोग करने के लिए अपनी इच्छित भाषा का चयन करें!",
  "personal_detail": "व्यक्तिगत विवरण",
  "enter_fullname": "पूरा नाम दर्ज करें",
  "enter_otp": "6 अंकों का OTP दर्ज करें",
  "next": "आगे",
  "future_date/time_not_allowed": "भविष्य की तारीख/समय की अनुमति नहीं है",
  "dairy_center_detail": "डेयरी केंद्र विवरण",
  "enter_dairyname": "डेयरी का नाम दर्ज करें",
  "enter_village_name": "गाँव का नाम दर्ज करें",
  "enter_taluka_name": "तालुका का नाम दर्ज करें",
  "enter_pincode_number": "पिनकोड नंबर दर्ज करें",
  "select_state": "राज्य चुनें",
  "enter_district": "जिले का नाम दर्ज करें",
  "app_update_available": "ऐप अपडेट उपलब्ध है!",
  "app_update_message":
      "ऐप का एक नया संस्करण उपलब्ध है। कृपया डेयरी विकास का उपयोग जारी रखने के लिए अपडेट करें।",
  "update_now": "अपडेट करें",
  "please_select_time_also": "कृपया समय भी चुनें",
  "loading": "लोड हो रहा है...",
  "select_district": "जिला चुनें",
  "dairy_center_settings": "डेयरी केंद्र सेटिंग्स",
  "select_collection_type": "संग्रह प्रकार चुनें",
  "select_milk_type": "दूध का प्रकार चुनें",
  "select_collection_shift": "संग्रह शिफ्ट चुनें",
  "select_payment_period": "भुगतान अवधि चुनें",
  "upgrade_now": "अभी अपग्रेड करें",
  "free_trial_msg": "फ्री ट्रायल @days दिनों में समाप्त होगा",
  "operations": "संचालन",
  "farmer_finance": "किसान एवं वित्त",
  "insights_communication": "अंतर्दृष्टि एवं संचार",
  "verify": "सत्यापित करें",
  "verify_otp": "OTP सत्यापित करें",
  "edit": "बदलें",
  "resend_otp": "ओटीपी फिर भेजें",
  "skip": "छोड़ें",
  "dariy_details_added": "डेयरी विवरण सफलतापूर्वक जोड़े गए!",
  "dairy_details_missing": "डेयरी विवरण अधूरे हैं",
  "select_option": "विकल्प चुनें",
  "add_photo": "फ़ोटो जोड़ें",
  "remove_thought": "विचार हटाएँ",
  "change_photo": "फ़ोटो बदलें",
  "add_text_thought": "टेक्स्ट विचार जोड़ें",
  "view_thought": "विचार देखें",
  "add_photo_thought": "फ़ोटो विचार जोड़ें",
  "choose_photo": "फ़ोटो चुनें",
  "terms_and_conditions": "नियम और शर्तें",
  "i_have_agree": "मैंने पढ़ लिया है और इससे सहमत हूँ ",
  "camera": "कैमरा",
  "gallary": "गैलरी",
  "verified": "सत्यापित",
  "free_trail_expired": "फ्री ट्रायल समाप्त हो गया!",
  "details_missing": "जानकारी उपलब्ध नहीं है!",
  "add_details": "जानकारी जोड़ें",
  "delete_account_warning":
      "आपका पूरा डेटा और खाता स्थायी रूप से हटा दिया जाएगा। क्या आप आगे बढ़ना चाहते हैं?",
  "request_sent": "अनुरोध भेज दिया गया",
  "delete_account": "खाता हटाएं",
  "account_delete_msg": "आपका खाता 1-2 दिनों के भीतर हटा दिया जाएगा। ",
  "account_withdraw_msg": "क्या आप खाता हटाने का अनुरोध वापस लेना चाहते हैं?",
  "withdraw": "वापस लें?",
  "app_logout_msg": "आप ऐप से लॉग आउट हो जाएंगे। क्या आप जारी रखना चाहते हैं?",
  "logout": "लॉग आउट",
  "dairy_details_missing_msg":
      "डेयरी की जानकारी उपलब्ध नहीं है। ऐप की सुविधाओं का उपयोग जारी रखने के लिए कृपया डेयरी विवरण जोड़ें।",
  "free_trial_expired_msg_part1":
      "आपका 7 दिनों का फ्री ट्रायल समाप्त हो गया है। \nसभी प्रीमियम सुविधाओं का उपयोग जारी रखने के लिए ",
  "free_trial_expired_msg_part2": "डेयरी साथी",
  "free_trial_expired_msg_part3": "\nकृपया अपना प्लान अपग्रेड करें।",
  "maybe_later": "शायद बाद में",
  "forgot_password": "पासवर्ड भूल गए",
  "enter_registred_mobile_number": "पंजीकृत मोबाइल नंबर दर्ज करें",
  "enter_otp_number": "ओटीपी दर्ज करें",
  "enter_new_password": "नया पासवर्ड दर्ज करें",
  "get_otp": "ओटीपी प्राप्त करें",

  "reset_password": "पासवर्ड रीसेट करें",
  "press_again_to_exit": "बाहर निकलने के लिए फिर से दबाएं",
  "unavailable": "उपलब्ध नहीं",
  "unknown": "अज्ञात",
  //error messages
  "we_have_sent_otp": "हमने आपके नंबर पर OTP भेज दिया है",
  "accept_terms": "कृपया नियम और शर्तों को स्वीकार करें",
  "name_required": "नाम आवश्यक है",
  "otp_required": "6 अंकों का ओटीपी दर्ज करें",
  "invalid_name": "नाम मान्य नहीं है",
  "phone_required": "फ़ोन नंबर आवश्यक है",
  "invalid_phone": "फ़ोन नंबर मान्य नहीं है",
  "password_required": "पासवर्ड आवश्यक है",
  "password_length": "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
  "invalid_pincode": "अमान्य पिनकोड",
  "dairyname_required": "डेयरी का नाम आवश्यक है",
  "village_name_required": "गाँव का नाम आवश्यक है",
  "taluka_name_required": "तालुका नाम आवश्यक है",
  "pincode_required": "पिनकोड आवश्यक है",
  "district_required": "जिले का चयन आवश्यक है",
  "state_required": "राज्य का चयन आवश्यक है",
  "chart_name_required": "चार्ट का नाम आवश्यक है",
  "invalid_chart_name": "चार्ट का नाम अमान्य है",

  "fat": "फैट",
  "fat_from": "फैट\nसे",
  "fat_to": "फैट\nतक",
  "snf_from": "एसएनएफ\nसे",
  "snf_to": "एसएनएफ\nतक",
  "clr_from": "सीएलआर\nसे",
  "clr_to": "सीएलआर\nतक",

  "fat_from2": "फैट से",
  "fat_to2": "फैट तक",
  "snf_from2": "एसएनएफ से",
  "snf_to2": "एसएनएफ तक",

  "snf": "एसएनएफ",
  "fat_snf": "फैट / एसएनएफ",
  "clr": "सीएलआर",
  "fat_clr": "फैट / सीएलआर",

  "add_fat_step": "फैट स्टेप जोड़ें",
  "add_snf_step": "एसएनएफ स्टेप जोड़ें",
  "add_clr_step": "सीएलआर स्टेप जोड़ें",

  "bonus_penalty": "बोनस / पेनल्टी",
  "bonus_penalty_on_fat": "फैट पर बोनस / पेनल्टी",
  "bonus_penalty_on_snf": "एसएनएफ पर बोनस / पेनल्टी",
  "bonus_penalty_on_clr": "सीएलआर पर बोनस / पेनल्टी",

  "from": "से",
  "to": "तक",
  "rate": "रेट",
  "add": "जोड़ें",

  "add_dynamic": "@type जोड़ें",
  "add_bonus": "बोनस जोड़ें",
  "add_penalty": "पेनल्टी जोड़ें",

  "bonus": "बोनस",
  "penalty": "पेनल्टी",

  "rate_chart": "रेट चार्ट",
  "fat_only": "फैट",
  "base_amount": "बेस अमाउंट",

  "add_step": "स्टेप जोड़ें",
  "add_bonus_penalty": "बोनस / पेनल्टी जोड़ें",
  "add_total_solid_step": "टोटल सॉलिड स्टेप जोड़ें",

  "step": "स्टेप",
  "amount": "राशि",
  "select_chart_type_format":
      "अपना नया चार्ट बनाने के लिए\nचार्ट का प्रकार और फ़ॉर्मेट चुनें।",
  "add_rate_chart": "रेट चार्ट जोड़ें",
  "save": "सहेजें",
  "select_formate": "फ़ॉर्मेट चुनें",
  "select_chart_type": "चार्ट का प्रकार चुनें",
  "enter_chart_name": "चार्ट का नाम दर्ज करें",
  "enter_fixed_rate": "स्थिर दर दर्ज करें",
  "add_fixed_rate": "स्थिर दर जोड़ें",
  "fixed_rate": "स्थिर दर",
  "change": "बदलें",
  "update": "बदलें",
  "adjustment": "समायोजन: ",
  "edit_rate_chart": "रेट चार्ट संपादित करें",
  "rate_charts": "रेट चार्ट",
  "no_rate_charts_found": "कोई रेट चार्ट नहीं मिला!",
  "add_now": "अभी जोड़ें",
  "no_chart_available": "चार्ट उपलब्ध नहीं है",
  "assign_to": "को सौंपें ",
  "select_chart_shift": "चार्ट शिफ्ट चुनें",
  "assign_already": "पहले से सौंपा गया",
  "assign": "सौंपें",
  "type": "प्रकार",
  "sno": "संख्या",
  "select_to_assign": "सौंपने के लिए चुनें",
  "assign_rate_chart": "रेट चार्ट सौंपें",
  "assigned_dynamic": "सौंपे गए (@count)",
  "selected_dynamic": "चयनित (@count)",
  "selecte_all": "सभी चुनें",
  "show_selected": "चयनित दिखाएँ",
  "unassign": "हटाएँ",
  "search_supplier": "नाम या कोड से ग्राहक खोजें",
  "milk_type": "दूध का प्रकार: ",
  "cow_milk": "गाय का दूध",
  "buffalo_milk": "भैंस का दूध",
  "category": "श्रेणी: ",
  "collection": "संग्रह",
  "milk_sale": "दूध बिक्री",
  "applied_to": "लागू किया गया: ",
  "dairy_dynamic": "डेयरी (@count)",
  "supplier_dynamic": "आपूर्तिकर्ता (@count)",
  "delete": "हटाएँ",
  "inactive": "निष्क्रिय",
  "all": "सभी",
  "active": "सक्रिय",
  "assigned": "सौंपा गया",
  "morning": "सुबह",
  "evening": "शाम",
  "morning_evening": "सुबह + शाम",
  "yes": "हाँ",
  "cancel": "रद्द करें",
  "cow_buffalo": "गाय + भैंस",
  "buffalo": "भैंस",
  "cow": "गाय",
  "choose_excel": "एक्सेल चुनें: ",
  "select_excel": "अपनी एक्सेल फ़ाइल चुनें",
  "choose": "चुनें",
  "upload": "अपलोड",
  "adjust_rate_chart_amount": "रेट चार्ट राशि समायोजित करें",
  "please_enter_adjustment_amount": "कृपया समायोजन राशि दर्ज करें",

  // milk suppliers strings....
  "update_supplier": "आपूर्तिकर्ता अपडेट करें",
  "add_supplier": "आपूर्तिकर्ता जोड़ें",
  "enter_supplier_code": "आपूर्तिकर्ता कोड दर्ज करें",
  "enter_supplier_name": "आपूर्तिकर्ता नाम दर्ज करें",
  "select_status": "स्थिति चुनें",
  "supplier_details": "आपूर्तिकर्ता विवरण",
  "supplier_code": "आपूर्तिकर्ता कोड",
  "full_name": "पूरा नाम",
  "supplier_mobile": "आपूर्तिकर्ता मोबाइल",
  "supplier_email": "आपूर्तिकर्ता ईमेल",
  "status": "स्थिति",
  "added_on": "जोड़ा गया",
  "remove_supplier": "आपूर्तिकर्ता हटाएं",
  "no_inactive_supplier_found": "कोई निष्क्रिय आपूर्तिकर्ता नहीं मिला",
  "no_supplier_found": "कोई आपूर्तिकर्ता नहीं मिला",
  "active:": "सक्रिय:",
  "inactive:": "निष्क्रिय:",
  "remove_supplier_warning_message":
      "क्या आप वाकई @supplierName को हटाना चाहते हैं?",
  "total:": "कुल:",
  "warning": "चेतावनी!",
  "supplier_active_inactive_message":
      "यह आपूर्तिकर्ता सक्रिय है, क्या आप इसे निष्क्रिय करना चाहते हैं?",
  "supplier_inactive_active_message":
      "यह आपूर्तिकर्ता निष्क्रिय है, क्या आप इसे सक्रिय करना चाहते हैं?",
  "suppliers": "आपूर्तिकर्ता",
  "actions": "क्रियाएँ",
  "no_unassigned_supplier": "कोई अनअसाइन किया गया सप्लायर उपलब्ध नहीं है",

  "all_supplier": "सभी आपूर्तिकर्ता",
  "no_assigned_supplier": "कोई सप्लायर असाइन नहीं है",
  "code:": "कोड: @code",
  "unassign_to": "अनअसाइन करें",
  "delete_rate_chart_warning":
      "इस चार्ट को हटाने के बाद सभी असाइनमेंट हटा दिए जाएंगे। क्या आप इसे हटाना चाहते हैं?",
  "activate_rate_chart_warning":
      "यह रेट चार्ट निष्क्रिय है। क्या आप इस चार्ट को सक्रिय करना चाहते हैं?",
  "inactivate_rate_chart_warning":
      "यह रेट चार्ट सक्रिय है। क्या आप इसे निष्क्रिय करना चाहते हैं? निष्क्रिय करने के बाद सभी असाइनमेंट हटा दिए जाएंगे।",

  /* ---------------- Rate Chart Error Messages ---------------- */
  "rate.fat_required": "फैट के मान और रेट आवश्यक हैं",
  "rate.snf_required": "एसएनएफ के मान और रेट आवश्यक हैं",
  "rate.clr_required": "सीएलआर के मान और रेट आवश्यक हैं",

  "rate.fat_range": "फैट की सीमा 2.0 से 15.0 तक है",
  "rate.snf_range": "एसएनएफ की सीमा 4.0 से 15.0 तक है",
  "rate.clr_range": "सीएलआर की सीमा 20.0 से 32.0 तक है",

  "rate.fat_step_required": "फैट स्टेप और राशि आवश्यक है",
  "rate.snf_step_required": "एसएनएफ स्टेप और राशि आवश्यक है",
  "rate.clr_step_required": "सीएलआर स्टेप और राशि आवश्यक है",

  "rate.fat_step_range": "फैट स्टेप की सीमा 2.0 से 15.0 तक है",
  "rate.snf_step_range": "एसएनएफ स्टेप की सीमा 4.0 से 15.0 तक है",
  "rate.clr_step_range": "सीएलआर स्टेप की सीमा 20.0 से 32.0 तक है",

  "rate.step_greater_than": "@type स्टेप @value से अधिक होना चाहिए",

  "rate.fat_snf_required": "फैट, एसएनएफ के मान और रेट आवश्यक हैं",
  "empty_rate_chart": "आपका रेट चार्ट खाली है",
  "upload_excel_file": "कृपया केवल एक्सेल फ़ाइल अपलोड करें",
  "select_at_least_shift": "कृपया कम से कम एक शिफ्ट चुनें",

  // collection strings....
  "update_collection": "संग्रह अपडेट करें",
  "add_collection": "संग्रह जोड़ें",
  "select_date": "तारीख चुनें",
  "select_suppliers": "आपूर्तिकर्ता चुनें",
  "search": "खोजें",
  "sample": "नमूना",
  "is_inactive": "@name निष्क्रिय है",
  "enter_liter": "लीटर दर्ज करें",
  "enter_fat": "फैट दर्ज करें",
  "enter_snf": "एसएनएफ दर्ज करें",
  "add_can": "कैन जोड़ें",
  "can_count": "कैन: @count",
  "total_cans_added": "कुल कैन जोड़े गए",
  "total_liter": "कुल लीटर",
  "total_amount": "कुल राशि",
  "previous": "पिछला",
  "w_scale": "वेट स्केल",
  "can": "कैन",
  "code_count": "कोड: @count",
  "adjust_collection": "संग्रह समायोजित करें",
  "search_suppliers_by_code_message":
      "@start से @end तक आपूर्तिकर्ताओं का संग्रह खोजने के लिए कोड दर्ज करें और नीचे दिया गया बटन दबाएं",
  "select_date_range": "तारीख की सीमा चुनें",
  "no_date_range_available": "कोई तारीख सीमा उपलब्ध नहीं है!",
  "code": "कोड",
  "search_collection": "संग्रह खोजें",
  "collections": "संग्रह",
  "show_full_data": "पूरा डेटा दिखाएँ",
  "hide_full_data": "पूरा डेटा छुपाएँ",
  "liter": "लीटर",
  "no_collection_found": "कोई संग्रह नहीं मिला!",
  "sort_by": "इसके अनुसार क्रमबद्ध करें",
  "absent:": "अनुपस्थित: ",
  "present:": "उपस्थित: ",
  "collection_adjustment": "संग्रह समायोजन",
  "print": "प्रिंट करें",
  "download_excel": "एक्सेल डाउनलोड करें",
  "sms_status": "एसएमएस स्थिति",
  "update_collection_rate": "संग्रह दर अपडेट करें",
  "collection_sheet": "संग्रह शीट",
  "names/details": "नाम / विवरण",
  "shift/type": "शिफ्ट / प्रकार",
  "fat: ": "फैट: ",
  "snf: ": "एसएनएफ: ",
  "sort_by_time": "समय के अनुसार क्रमबद्ध करें",
  "sort_by_amount_ascending": "राशि (आरोही) के अनुसार क्रमबद्ध करें",
  "sort_by_amount_descending": "राशि (अवरोही) के अनुसार क्रमबद्ध करें",

  // collection validation messages
  "select_a_date_to_add_collection": "संग्रह जोड़ने के लिए कृपया तारीख चुनें",
  "select_a_supplier_first": "कृपया पहले एक आपूर्तिकर्ता चुनें",
  "please_select_a_active_supplier": "कृपया एक सक्रिय आपूर्तिकर्ता चुनें",
  "please_add_collection_liter": "कृपया संग्रह की लीटर मात्रा जोड़ें",
  "remove_collection_message":
      "सारा डेटा खो जाएगा, क्या आप इस संग्रह को हटाना चाहते हैं?",
  "please_add_fat_point": "कृपया फैट पॉइंट जोड़ें",
  "please_add_snf_or_clr_point": "कृपया एसएनएफ या सीएलआर पॉइंट जोड़ें",
  "rate_is_empty": "दर खाली है",

  // milk sale strings....
  "add_sale": "दूध बिक्री जोड़ें",

  "update_sale": "बिक्री अपडेट करें",
  "milk_buyers": "दूध खरीदने वाले",
  "bill": "बिल",
  "no_milksale_found": "कोई दूध बिक्री नहीं मिली!",
  "update_buyer": "खरीदार अपडेट करें",
  "add_buyer": "खरीदार जोड़ें",
  "fixed_cow_rate": "निश्चित गाय दर",
  "fixed_buffalo_rate": "निश्चित भैंस दर",
  "enter_buyer_code": "खरीदार कोड दर्ज करें",
  "enter_buyer_name": "खरीदार का नाम दर्ज करें",
  "select_rate_type": "दर प्रकार चुनें",
  "fixed_milk_sale_rate": "निश्चित दूध बिक्री दर",
  "all_buyers": "सभी खरीदार",
  "no_buyer_found": "कोई खरीदार नहीं मिला",
  "search_buyer": "खरीदार खोजें",
  "remove": "हटाएँ",
  "buyers_active_inactive_message":
      "यह खरीदार सक्रिय है, क्या आप इसे निष्क्रिय करना चाहते हैं?",
  "buyers_inactive_active_message":
      "यह खरीदार निष्क्रिय है, क्या आप इसे सक्रिय करना चाहते हैं?",
  "buyers": "खरीदार",
  "date_can_not_be_change": "तारीख बदली नहीं जा सकती",
  "select_a_date_to_add_sale": "बिक्री जोड़ने के लिए तारीख चुनें",
  "select_a_buyer_first": "कृपया पहले एक खरीदार चुनें",
  "select_a_active_buyer": "कृपया एक सक्रिय खरीदार चुनें",
  "please_add_sale_liter": "कृपया बिक्री के लीटर जोड़ें",

  // foos strings...
  "food_dealers": "खाद्य विक्रेता",
  "no_dealer_found": "कोई विक्रेता नहीं मिला!",
  "search_dealer": "नाम या कोड से विक्रेता खोजें",
  "add_dealer": "विक्रेता जोड़ें",
  "update_dealer": "विक्रेता अपडेट करें",
  "enter_dealer_code": "विक्रेता कोड दर्ज करें",
  "add_food_sale": "चारा बिक्री जोड़ें",
  "update_food_sale": "चारा बिक्री अपडेट करें",
  "search_supplier_or_buyer": "आपूर्तिकर्ता या खरीदार खोजें",
  "enter_food_rate": "चारा का रेट दर्ज करें",
  "enter_dealer_name": "विक्रेता का नाम दर्ज करें",
  "enter_dealer_address": "विक्रेता का पता दर्ज करें",
  "enter_dealer_remark": "टिप्पणी दर्ज करें",
  "all_items": "सभी आइटम",
  "no_item_available": "कोई आइटम उपलब्ध नहीं है",
  "search_item": "आइटम खोजें",
  "added_by": "जोड़ा गया द्वारा",
  "added_by_you": "आपके द्वारा जोड़ा गया",
  "edit_your_item": "अपना आइटम संपादित करें",
  "add_your_item": "अपना आइटम जोड़ें",
  "add_item": "आइटम जोड़ें",
  "enter_your_item_name": "अपने आइटम का नाम दर्ज करें",
  "add_stock": "स्टॉक जोड़ें",
  "update_stock": "स्टॉक अपडेट करें",
  "select_items_to_add": "जोड़ने के लिए आइटम चुनें",
  "enter_food_qty": "खाद्य मात्रा दर्ज करें",
  "enter_buy_rate": "खरीद दर दर्ज करें",
  "enter_sale_rate": "बिक्री दर दर्ज करें",
  "unit": "इकाई",
  "search_unit": "इकाई खोजें",
  "select_food": "खाद्य चुनें",
  "dealer_code": "विक्रेता कोड दर्ज करें",
  "select_dealer": "विक्रेता चुनें",
  "food_stock": "खाद्य स्टॉक",
  "added": "जोड़ा गया: @date",
  "in_stock": "स्टॉक में",
  "out_of_stock": "स्टॉक समाप्त",
  "total_qty": "कुल मात्रा",
  "units": "इकाई",
  "sold/stock": "बिक्री/स्टॉक",
  "sale_rate": "बिक्री दर",
  "history": "इतिहास",
  "food_stock_empty": "खाद्य स्टॉक खाली है",
  "stock_history": "स्टॉक इतिहास",
  "per": "प्रति @count",
  "buy_price": "खरीद मूल्य",
  "in_stock_lower": "स्टॉक में",
  "out_of_stock_lower": "स्टॉक समाप्त",
  "no_history_found": "कोई इतिहास नहीं मिला!",
  "food_sales": "खाद्य बिक्री",
  "update_date": "अपडेट किया गया: @date",
  "created_date": "बनाया गया: @date",

  // food validation messages
  "select_dealer_first": "पहले विक्रेता चुनें",
  "please_select_food": "कृपया पहले खाद्य चुनें",
  "enter_food__buy_rate": "खाद्य की खरीद दर दर्ज करें",
  "enter_food__sale_rate": "खाद्य की बिक्री दर दर्ज करें",

  "today": "आज",
  "this_week": "इस सप्ताह",
  "this_month": "इस महीने",
  "last_month": "पिछला महीना",
  "custom": "कस्टम",

  // notice strings...
  "notice_posts": "सूचना पोस्ट",
  "posted_on": "पोस्ट किया गया: @date",
  "no_post_yet": "अभी तक कोई पोस्ट नहीं जोड़ी गई!",
  "add_post": "पोस्ट जोड़ें",
  "update_post": "पोस्ट अपडेट करें",
  "update_your_notice": "अपनी सूचना अपडेट करें",
  "create_new_notice": "नई सूचना बनाएं",
  "write_message_to_user":
      "अपने ग्राहकों को संदेश लिखें (जैसे: आज नया स्टॉक उपलब्ध है)...",
  "limited_reached": "(सीमा पूरी हो गई!)",
  "post_now": "अभी पोस्ट करें",
  "customers_will_see_message": "केवल आपके ग्राहक ही \nआपकी पोस्ट देख पाएंगे।",
  "post_remove_message":
      "यह पोस्ट हमेशा के लिए हट जाएगी और इसे पुनर्स्थापित नहीं किया जा सकता। क्या आप फिर भी इसे हटाना चाहते हैं?",
  "remove_post": "पोस्ट हटाएं",
  "please_write_some_message": "कृपया कुछ संदेश लिखें",

  // invoice strings...
  "customer_invoices": "ग्राहक चालान",
  "food_or_item_amount": "खाद्य या वस्तु राशि: ",
  "user": "उपयोगकर्ता: ",
  "status_dynamic": "स्थिति: ",
  "paid": "भुगतान किया गया",
  "pending": "लंबित",
  "amount_dynamic": "राशि: @amount",
  "mark_paid": "भुगतान चिह्नित करें",
  "mark_receive": "प्राप्त चिह्नित करें",
  "no_invoice_found": "कोई चालान नहीं मिला!",
  "search_invoice_by_name_or_code": "नाम या राशि से चालान खोजें",
  "genrate_invoice": "चालान बनाएं",
  "invoice_details": "चालान विवरण",
  "total_of_date": "@date का कुल",
  "dealer_up": "डीलर",
  "supplier_up": "आपूर्तिकर्ता",
  "buyer_up": "खरीदार",
  "total_collection_amount": "कुल संग्रह राशि",
  "total_deduction": "कुल कटौती",
  "amount_due": "देय राशि",
  "food_or_item": "खाद्य या वस्तु",
  "edit_up": "संपादित करें",
  "product_name_up": "उत्पाद का नाम",
  "deduction_details": "कटौती विवरण",
  "deduction_type": "कटौती प्रकार",
  "total_up": "कुल",
  "collections_up": "संग्रह",
  "invoice_genrate": "चालान तैयार",
  "delete_invoice": "क्या आप वाकई इस चालान को हटाना चाहते हैं?",

  // khata strings...
  "add_customer": "ग्राहक जोड़ें",
  "call": "कॉल",
  "payee": "@count देयकर्ता",
  "receivalbes": "@count प्राप्य",
  "you_will_give": "आप देंगे",
  "you_will_get": "आप प्राप्त करेंगे",
  "balance": "शेष राशि",
  "all_entries": "सभी प्रविष्टियाँ",
  "current_balance": "वर्तमान राशि",
  "got": "प्राप्त",
  "gave": "दिया",
  "gotr": "प्राप्त ₹",
  "gaver": "दिया ₹",
  "you_are_paying": "आप भुगतान कर रहे हैं",
  "you_are_receving": "आप प्राप्त कर रहे हैं",
  "enter_amount": "राशि दर्ज करें",
  "enter_a_note": "टिप्पणी दर्ज करें",
  "no_record_found": "कोई खाता रिकॉर्ड नहीं मिला!",
  "no_khata_customer_available": "कोई खाता ग्राहक नहीं मिला",
  "delete_entry_msg":
      "यह एंट्री हमेशा के लिए हट जाएगी। क्या आप पक्का जारी रखना चाहते हैं?",
  "note_unavailable": "टिप्पणी उपलब्ध नहीं है",
  "no_entries_found": "कोई प्रविष्टि नहीं मिली!",
  "add_khata_customer": "खाता ग्राहक जोड़ें",
  "update_khata_customer": "खाता ग्राहक अपडेट करें",
  "enter_customer_name": "ग्राहक का नाम दर्ज करें",
  "select_from_contacts": "संपर्कों से चुनें",
  "delete_customer_msg": "क्या आप वाकई @name को हटाना चाहते हैं?",
  "dairy_sathi_khata": "डेयरी साथी खाता",
  "transaction_record_msg":
      "इस ग्राहक के लिए लेन-देन स्वचालित रूप से \nरिकॉर्ड किए जाएंगे।",
  "please_enter_amount": "कृपया राशि दर्ज करें",
  "enter_valid_amount": "मान्य राशि दर्ज करें",

  // Subscripiton plan strings
  "subscriptions": "सदस्यता योजनाएं",
  "choose_plan": "अपनी सदस्यता चुनें",
  "choose_plan_msg":
      "अपनी पसंदीदा सदस्यता चुनें और डेयरी साथी के साथ अपने व्यवसाय को बढ़ाएं",
  "no_plans_found": "कोई सदस्यता नहीं मिली!",
  "best_value": "सबसे अच्छा मूल्य",
  "payment_failed": "भुगतान असफल रहा!",
  "payment_success": "भुगतान सफल!",
  "plan_upgrade_message": "आपकी सदस्यता योजना सफलतापूर्वक अपडेट हो गई है!",
  "transaction_details": "लेन-देन विवरण",
  "txnt_id": "लेन-देन आईडी",
  "d&t": "दिनांक और समय",
  "payment_method": "भुगतान का तरीका",
  "plan": "योजना",
  "payment_status": "भुगतान स्थिति",
  "download_receipt": "रसीद डाउनलोड करें",
  "go_to_dashboard": "डैशबोर्ड पर जाएं",
  "txs_fail_msg":
      "आपका लेन-देन पूरा नहीं हो सका। यह कम बैलेंस या बैंक सर्वर की अस्थायी समस्या के कारण हो सकता है।",
  "amt": "राशि",
  "txnt_id_UP": "लेन-देन आईडी",
  "date_up": "दिनांक",
  "need_help": "तुरंत सहायता चाहिए?",
  "support_msg":
      "हमारी सहायता टीम 24/7 उपलब्ध है\nभुगतान से संबंधित सवालों के लिए",
  "retry_payment": "भुगतान पुनः प्रयास करें",
  "success": "सफल",
};
